In [1]:
import pandas as pd
import numpy as np

# Look at data from insideAirbnb

In [3]:
listings_ia2 = pd.read_csv('listings 2.csv')

In [4]:
listings_ia2

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,1810172,https://www.airbnb.com/rooms/1810172,20151002231814,2015-10-03,Room for 2 in Rozzie - Full Bath,This second floor bedroom sleeps two in a quee...,NaN,This second floor bedroom sleeps two in a quee...,none,Our neighborhood is quiet and relaxed. There i...,...,9,f,NaN,NaN,f,flexible,f,f,2,0.64
1,6976,https://www.airbnb.com/rooms/6976,20151002231814,2015-10-03,Mexican Folk Art Haven in Boston,"Come stay with a friendly, middle-aged guy in ...",This is a well-maintained two-family house bui...,"Come stay with a friendly, middle-aged guy in ...",none,The LOCATION: Roslindale is a safe and diverse...,...,9,f,NaN,NaN,f,moderate,t,f,1,0.42
2,3075044,https://www.airbnb.com/rooms/3075044,20151002231814,2015-10-03,Charming room in pet friendly apt,Charming and quiet room in a second floor 1910...,Small but cozy and quite room with a full size...,Charming and quiet room in a second floor 1910...,none,"The room is in Roslindale, a diverse and prima...",...,10,f,NaN,NaN,f,moderate,f,f,1,1.22
3,4283698,https://www.airbnb.com/rooms/4283698,20151002231814,2015-10-03,Private 1 bedroom w/ kitchenette,"This is a fantastic, newly updated space. Lar...",This is a fantastic space! We've finished all...,"This is a fantastic, newly updated space. Lar...",none,We're just a few blocks from the shops and res...,...,8,f,NaN,NaN,f,strict,f,f,1,2.09
4,4085362,https://www.airbnb.com/rooms/4085362,20151002231814,2015-10-03,"Sub""Urban"" Vacationing Rm 2",Come share our beautifully maintained grand t...,We provide a bedroom and a full shared bath fo...,Come share our beautifully maintained grand t...,none,Roslindale is one of the neighborhoods of Bost...,...,10,f,NaN,NaN,f,moderate,t,t,2,1.03
5,225834,https://www.airbnb.com/rooms/225834,20151002231814,2015-10-03,Skyline View to Boston,High atop Metropolitan Hill. Expansive view. N...,After a good nights' sleep you will wake each ...,High atop Metropolitan Hill. Expansive view. N...,none,This is a very quiet neighborhood. Guests ofte...,...,9,f,NaN,NaN,t,strict,f,f,2,0.68
6,7252607,https://www.airbnb.com/rooms/7252607,20151002231814,2015-10-03,Private Room near Public Transport,A handsome colonial house set on a tranquil si...,NaN,A handsome colonial house set on a tranquil si...,none,NaN,...,9,f,NaN,NaN,f,strict,f,f,3,0.78
7,1936861,https://www.airbnb.com/rooms/1936861,20151002231814,2015-10-03,Private Room in Rozzie,Private room with twin bed. Walking distance t...,"Simple, private space with a surprising amount...",Private room with twin bed. Walking distance t...,none,"This is a super fun neighborhood in Boston, bu...",...,10,f,NaN,NaN,f,flexible,f,f,1,4.00
8,225979,https://www.airbnb.com/rooms/225979,20151002231814,2015-10-03,Cozy Room & Fresh Roasted Coffee,Fresh home roasted coffee from around the worl...,"This is a charming, bright, and sunny apartmen...",Fresh home roasted coffee from around the worl...,none,This is a very quiet neighborhood. So quiet yo...,...,10,f,NaN,NaN,t,strict,f,f,2,1.20
9,2583074,https://www.airbnb.com/rooms/2583074,20151002231814,2015-10-03,Cozy room in a charming villa.,My home is a villa in one of the frien...,The room is cozy and private. The house is les...,My home is a villa in one of the frien...,none,"This a nice multicultural, family neighborhood...",...,10,f,NaN,NaN,f,flexible,f,f,2,1.24
10,6933545,https://www.airbnb.com/rooms/6933545,20151002231814,2015-10-03,Cozy Room On the Arnold Arboretum,The apartment is on the first floor of a class...,This is a sunny and cozy apartment for male or...,The apartment is on the first floor of a class...,none,"This is a very quiet neighborhood, which is gr...",...,9,f,NaN,NaN,f,moderate,f,f,1,7.28
11,5434353,https://www.airbnb.com/rooms/5434353,20151002231814,2015-10-03,Quiet Beauty in Boston,Enjoy the full space of our home as you explor...,Large living and dining area. Sprawling space....,Enjoy the full space of our home as you explor...,none,"Quiet Roslindale, close to the trendy Jamaica ...",...,10,f,NaN,NaN,f,strict,f,f,1,0.91
12,4025194,https://www.airbnb.com/rooms/4025194,20151002231814,2015-10-03,Queen Bed/Near Subway/Free Passes,"Comfy queen-size bed, free breakfast, clean sh...",This room is situated in Boston's charming Ros...,"Comfy queen-size bed, free breakfast, clean sh...",none,Roslindale is a fun neighborhood in Boston. It...,...,10,f,NaN,NaN,t,flexible,f,f,4,7.07
13,1591827,https://www.airbnb.com/rooms/1591827,20151002231814,2015-10-03,PrivRoom+Bath In Roslindale/Boston,Cozy room with private bathroom use in Roslind...,Our listing is a private room in a very conven...,Cozy room with private bathroom use in Roslind...,none,We are located minutes from Roslindale Village...,...,9,f,NaN,NaN,f,moderate,f,f,1,4.19
14,753446,https://www.airbnb.com/rooms/753446,20151002231814,2015-10-03,6 miles away from downtown Boston!,Nice and cozy apartment about 6 miles away to ...,Nice and cozy apartment about 6 miles away to ...,Nice and cozy apartment about 6 miles away to ...,none,NaN,...,9,f,NaN,NaN,f,moderate,f,f,1,7.00
15,3755609,https://www.airbnb.com/rooms/3755609,20151002231814,2015-10-03,Lovely & Gracious Victorian room,Lovely & Gracious Victorian room offers the be...,"The room is lovely, sunny, decorated with auth...",Lovely & Gracious Victorian room offers the be...,none,Today's residents of Roslindale are attracted...,...,9,f,NaN,NaN,f,flexible,f,f,1,1.02
16,5884429,https://www.airbnb.com/rooms/5884429,20151002231814,2015-10-03,"2 Rooms, Private Bath, AC -sleeps 4","My comfy, clean and relaxing home with AC is o...",You will have two bedrooms on the second floor...,"My comfy, clean and relaxing home with AC is o...",none,"Roslindale is a friendly, diverse, walkable ne...",...,10,f,NaN,NaN,f,flexible,f,f,4,1.96
17,879929,https://www.airbnb.com/rooms/879929,20151002231814,2015-10-03,Surround yourself with custom art!,NaN,One big bedroom in a three bedroom Apartment i...,One big bedroom in a three bedroom Apartment i...,none,This is a safe beautiful neighborhood borderin...,...,9,f,NaN,NaN,f,strict,f,f,1,1.40
18,1494726,https://www.airbnb.com/rooms/1494726,20151002231814,2015-10-03,Cozy in Rozzie!,"Spacious & quiet room with private bathroom, f...",Spacious room with private bathroom in really ...,"Spacious & quiet room with private bathroom, f...",none,"If you like quaint villages, come to Rozzie Sq...",...,9,f,NaN,NaN,t,strict,f,f,1,0.45
19,7651065,https://www.airbnb.com/rooms/7651065,20151002231814,2015-10-03,Come Home to Boston,"My comfy, clean and relaxing home is one block...","Clean, attractive, private room, one block fro...","My comfy, clean and relaxing home is one block...",none,"I love the proximity to downtown, the neighbor...",...,9,f,NaN,NaN,f,flexible,f,f,4,3.83
20,3420384,https://www.airbnb.com/rooms/3420384,20151002231814,2015-10-03,"Convient, Safe and Comfortable",Located along public transportation with plent...,"Extra large studio with wifi, cable, original ...",Located along public transportation with plent...,none,"Village 1 mile with banks, grocery store, spec...",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
21,8473851,https://www.airbnb.com/rooms/8473851,20151002231814,2015-10-03,Private Room in Single Family Home,"Sunny, smoke free home in a safe and nice nei...",The bedroom is on the second floor of a 2 stor...,"Sunny, smoke free home in a safe and nice nei...",none,"Neighborhood is welcoming, close to restaurant...",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
22,1668313,https://www.airbnb.com/rooms/1668313,20151002231814,2015-10-03,Room in Rozzie-Twin Bed-Full Bath,Quiet second floor bedroom sleeps one in comfo...,NaN,Quiet second floor bedroom sleeps one in comfo...,none,Our neighborhood is quiet and relaxed. There i...,...,9,f,NaN,NaN,f,flexible,f,f,2,0.50
23,3575220,https://www.airbnb.com/rooms/3575220,20151002231814,2015-10-03,The Artist room in beautiful villa.,"My home is a villa in one of the friendliest, ...",The room is spacious and private. The house is...,"My home is a villa in one of the friendliest, ...",none,"This a nice multicultural, family neighborhood.",...,10,f,NaN,NaN,f,flexible,f,f,2,0.53
24,4922204,https://www.airbnb.com/rooms/4922204,20151002231814,2015-10-03,Charming new house-15 min to Boston,Roslindale is the new hip section of Boston an...,I just bought this house so my old Airbnb list...,Roslindale is the new hip section of Boston an...,none,"Roslindale is the new hip area of Boston. ""The...",...,9,f,NaN,NaN,f,strict,f,f,3,5.09
25,1724900,https://www.airbnb.com/rooms/1724900,20151002231814,2015-10-03,Charming sunlit house in Boston,A beautiful house in Rolsindale village an att...,A cosy house on one floor with typical inside ...,A beautiful house in Rolsindale village an att...,none,Historic Boston/Cambridge area is easily acces...,...,9,f,NaN,NaN,f,strict,f,f,1,0.64
26,849408,https://www.airbnb.com/rooms/849408,20151002231814,2015-10-03,Perfect & Practical Boston Rental,This is a cozy and spacious one bedroom unit w...,Perfect apartment rental for those in town vis...,This is a cozy and spacious one bedroom unit w...,none,"This neighborhood truly has it all. Good, not...",...,9,f,NaN,NaN,f,strict,f,f,2,1.22
27,5759676,https://www.airbnb.com/rooms/5759676,20151002231814,2015-10-03,Perfect home away from home,Our comfortable home is the ideal spot to sta...,NaN,Our comfortable home is the ideal spot to sta...,none,NaN,...,10,f,NaN,NaN,f,flexible,f,f,1,0.81
28,3988018,https://www.airbnb.com/rooms/3988018,20151002231814,2015-10-03,Sports Room/Near Subway/Free Passes,"Comfy twin beds, free breakfast, clean sheets,...",This room is situated in Boston's charming Ros...,"Comfy twin beds, free breakfast, clean sheets,...",none,Roslindale is a fun neighborhood in Boston. It...,...,10,f,NaN,NaN,t,flexible,f,f,4,7.73
29,6242681,https://www.airbnb.com/rooms/6242681,20151002231814,2015-10-03,Rozzie condo with art & Goldens,"Comfy dog-friendly condo with great art, gas f...",NaN,"Comfy dog-friendly condo with great art, gas f...",none,NaN,...,10,f,NaN,NaN,f,flexible,f,f,1,3.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2528,8533578,https://www.airbnb.com/rooms/8533578,20151002231814,2015-10-03,Gorgeous Brookline/Boston home (#2),Recently remodeled unit in 2-family home near ...,"Beautiful, recently remodeled space with high-...",Recently remodeled unit in 2-family home near ...,none,This house is in the beautiful residential nei...,...,NaN,f,NaN,NaN,t,moderate,f,f,3,NaN
2529,4729833,https://www.airbnb.com/rooms/4729833,20151002231814,2015-10-03,"Two-bedroom, 1-bathroom",We are two Harvard students. We live in Grad ...,NaN,We are two Harvard students. We live in Grad ...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
2530,7619794,https://www.airbnb.com/rooms/7619794,20151002231814,2015-10-03,"Luxurious, spacey studio in Boston!","Modern, cozy and spacey loft. Excellent locati...",NaN,"Modern, cozy and spacey loft. Excellent locati...",none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,3,NaN
2531,8127009,https://www.airbnb.com/rooms/8127009,20151002231814,2015-10-03,Bright appartment-12' from downtown,"Nice apartment in Somerville, renovated Octobe...","The apartment is brand new, it was renovated i...","Nice apartment in Somerville, renovated Octobe...",none,"We live in East Somerville, very near Sullivan...",...,10,f,NaN,NaN,t,flexible,f,f,1,5.00
2532,6300161,https://www.airbnb.com/rooms/6300161,20151002231814,2015-10-03,Lux Brookline 2BR w/ gym & WiFi,This property is a newly renovated 3 story ele...,"Our beautiful apartments feature bay windows, ...",This property is a newly renovated 3 story ele...,none,"Living at this address, residents will enjoy t...",...,NaN,f,NaN,NaN,f,moderate,f,t,33,NaN
2533,7332266,https://www.airbnb.com/rooms/7332266,20151002231814,2015-10-03,"Sunny private room,Longwood, Fenway","Room is similar to a Dormitory, private room w...",Room is full of sunlight and is walking distan...,"Room is similar to a Dormitory, private room w...",none,St. Mary’s neighborhood marks an Eastern entra...,...,9,f,NaN,NaN,f,strict,f,f,3,5.00
2534,6958692,https://www.airbnb.com/rooms/6958692,20151002231814,2015-10-03,8min walk to Harvard Square-room 1,**New list from (phone number hidden) **Valuab...,This is the biggest room in this historical ap...,**New list from (phone number hidden) **Valuab...,none,NaN,...,5,f,NaN,NaN,t,strict,f,f,5,3.33
2535,5040534,https://www.airbnb.com/rooms/5040534,20151002231814,2015-10-03,Best safe location 1st Floor room 2,"2 minutes walk to T subway station, supermarke...","This floor have 3 bedrooms available, every th...","This floor have 3 bedrooms available, every th...",none,Location are close to everything 2 minutes to ...,...,9,f,NaN,NaN,f,moderate,f,f,5,0.71
2536,2083261,https://www.airbnb.com/rooms/2083261,20151002231814,2015-10-03,Beautiful Apart in Cambridgeport,"Depending on the dates, a big room with a shar...","Clean, spacious, and full of daylight. Living ...","Clean, spacious, and full of daylight. Living ...",none,The neighborhood is quiet and friendly. There...,...,NaN,f,NaN,NaN,f,flexible,f,f,1,0.59
2537,8516029,https://www.airbnb.com/rooms/8516029,20151002231814,2015-10-03,Private apartment close the city!,This private apartment is part of our home but...,"You will have a your own separate entrance, li...",This private apartment is part of our home but...,none,Dedham center is a cute little area with nice ...,...,NaN,f,NaN,NaN,f,moderate,f,t,1,NaN
2538,6093004,https://www.airbnb.com/rooms/6093004,20151002231814,2015-10-03,Private room near T,Big room near Sullivan T station. Bus station ...,NaN,Big room near Sullivan T station. Bus station ...,none,NaN,...,8,f,NaN,NaN,t,strict,f,f,15,3.18
2539,4438351,https://www.airbnb.com/rooms/4438351,20151002231814,2015-10-03,"skylit suite w/bath, porch, parking",Our skylit suite w/comfortable sofabed & full ...,NaN,Our skylit suite w/comfortable sofabed & full ...,none,NaN,...,10,f,NaN,NaN,f,strict,f,f,1,2.92
2540,7454474,https://www.airbnb.com/rooms/7454474,20151002231814,2015-10-03,A room in the village. Room 4,The fourth of four private rooms on the first ...,NaN,The fourth of four private rooms on the first ...,none,NaN,...,10,f,NaN,NaN,f,strict,f,f,1,0.54
2541,7005442,https://www.airbnb.com/rooms/7005442,20151002231814,2015-10-03,Cute 1br apt near Harvard Sq,This is an unfurnished 1 br apt with full bath...,NaN,This is an unfurnished 1 br apt with full bath...,none,NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
2542,2079649,https://www.airbnb.com/rooms/2079649,20151002231814,2015-10-03,8/1 nice/quiet Furn 1 bd in 2 bd TH,"Furnished Room in very nice,clean,elegant 2 Be...","Very nice! Furnished, Hardwood Floors, Clean....","Furnished Room in very nice,clean,elegant 2 Be...",none,"My complex is in a beautiful setting, brick at...",...,NaN,f,NaN,NaN,f,strict,f,f,1,NaN
2543,5593783,https://www.airbnb.com/rooms/5593783,20151002231814,2015-10-03,Quiet cozy room near T,"Clean, private room near T. Very easy to Down...",NaN,"Clean, private room near T. Very easy to Down...",none,NaN,...,8,f,NaN,NaN,t,strict,f,f,15,0.48
2544,5470315,https://www.airbnb.com/rooms/5470315,20151002231814,2015-10-03,Best safe location 2nd floor room 6,"2 minutes walk to T subway station, supermarke...",This room is biggest room of the 4 bedrooms av...,"2 minutes walk to T subway station, supermarke...",none,Location are close to everything 2 minutes to ...,...,9,f,NaN,NaN,f,moderate,f,f,5,1.68
2545,3701108,https://www.airbnb.com/rooms/3701108,20151002231814,2015-10-03,sunny furnished studio close to T,Absolutely gorgeous large studio located at Al...,"It is in the middle of BU and BC, more towards...",Absolutely gorgeous large studio located at Al...,none,NaN,...,9,f,NaN,NaN,f,strict,f,f,1,0.63
2546,5320198,https://www.airbnb.com/rooms/5320198,20151002231814,2015-10-03,"Comfy, rm Harvard Sq w Pvt. Ent/bth",This is a sunny 12' x 14' room with a private ...,Private room on 2nd floor of beautiful Victori...,This is a sunny 12' x 14' room with a private ...,none,"This is an historic neighborhood, only five bl...",...,NaN,f,NaN,NaN,f,strict,f,f,1,NaN
2547,6626424,https://www.airbnb.com/rooms/6626424,20151002231814,2015-10-03,"Two bed, Perfectly located, updated",Convenient and renovated apartment in a great ...,"The Space This is a rare find. Renovated, two...",Convenient and renovated apartment in a great ...,none,NaN,...,9,f,NaN,NaN,t,strict,f,f,2,3.00
2548,6956835,https://www.airbnb.com/rooms/6956835,20151002231814,2015-10-03,8min walk to Harvard Square-Room 4,**New list from (phone number hidden) **Valuab...,**New list from (phone number hidden) **Valuab...,**New list from (phone number hidden) **Valuab...,none,NaN,...,8,f,NaN,NaN,f,strict,f,f,5,3.28
2549,7763582,https://www.airbnb.com/rooms/7763582,20151002231814,2015-10-03,"5 min walk to Subway, 15 to Harvard",Its close to everywhere! 5 min walk to Orange ...,NaN,Its close to everywhere! 5 min walk to Orange ...,none,NaN,...,10,f,NaN,NaN,f,strict,f,f,7,0.86
2550,5874337,https://www.airbnb.com/rooms/5874337,20151002231814,2015-10-03,"Great 1 br, short walk to Harvard",Terrific 1 br apartment available. It is a 10 ...,Great apartment in a remodeled Harvard family ...,Terrific 1 br apartment available. It is a 10 ...,none,Quiet family neighborhood.,...,10,f,NaN,NaN,f,flexible,f,f,1,1.35
2551,394462,https://www.airbnb.com/rooms/394462,20151002231814,2015-10-03,Your pad - 10 Min to Boston center,Looking for the location close to the center o...,Come enjoy your private room with internet (wi...,Looking for the location close to the center o...,none,NaN,...,8,f,NaN,NaN,f,strict,f,f,2,0.86
2552,3051609,https://www.airbnb.com/rooms/3051609,20151002231814,2015-10-03,Female roommate; Close to Harvard,"Great location, lovely home. Super convenient,...","I have a furnished room for rent, all utilitie...","Great location, lovely home. Super convenient,...",none,"Super convenient, quiet, great neighbors.",...,9,f,NaN,NaN,f,moderate,f,f,1,0.36
2553,8118800,https://www.airbnb.com/rooms/8118800,20151002231814,2015-10-03,Convenient Harvard apartment!,Charming one bedroom apartment right next to H...,The entire apartment unit is private and can b...,Charming one bedroom apartment right next to H...,none,The apartment is RIGHT NEXT to Harvard's under...,...,NaN,f,NaN,NaN,t,moderate,f,f,1,2.81
2554,6185167,https://www.airbnb.com/rooms/6185167,20151002231814,2015-10-03,In the Heart of Brookline,Bright & cozy unit in the heart of Brookline V...,This unit is tucked in a safe cozy neighborhoo...,Bright & cozy unit in the heart of Brookline V...,none,Brookline Village is one of the most desirable...,...,10,f,NaN,NaN,f,moderate,f,f,1,3.80
2555,3448991,https://www.airbnb.com/rooms/3448991,20151002231814,2015-10-03,"Double Room, easy access to Boston",This is a comfortable room with a queen size b...,We have been hosting friends and relatives for...,This is a comfortable room with a queen size b...,none,We are in suburbia yet close to Boston. The B...,...,10,f,NaN,NaN,f,flexible,f,f,1,2.11
2556,7968929,https://www.airbnb.com/rooms/7968929,20151002231814,2015-10-03,Warm & Spacious 3BR by Flatbook,Located in one of Brookline's premier apartmen...,"In every Flatbook apartment, you’ll find: • Li...",Located in one of Brookline's premier apartmen...,none,"The apartment is located in Brookline, a town ...",...,10,f,NaN,NaN,t,moderate,f,f,19,2.00

In [5]:
listings_ia2.columns

Index([u'id', u'listing_url', u'scrape_id', u'last_scraped', u'name',
       u'summary', u'space', u'description', u'experiences_offered',
       u'neighborhood_overview', u'notes', u'transit', u'thumbnail_url',
       u'medium_url', u'picture_url', u'xl_picture_url', u'host_id',
       u'host_url', u'host_name', u'host_since', u'host_location',
       u'host_about', u'host_response_time', u'host_response_rate',
       u'host_acceptance_rate', u'host_is_superhost', u'host_thumbnail_url',
       u'host_picture_url', u'host_neighbourhood', u'host_listings_count',
       u'host_total_listings_count', u'host_verifications',
       u'host_has_profile_pic', u'host_identity_verified', u'street',
       u'neighbourhood', u'neighbourhood_cleansed',
       u'neighbourhood_group_cleansed', u'city', u'state', u'zipcode',
       u'market', u'smart_location', u'country_code', u'country', u'latitude',
       u'longitude', u'is_location_exact', u'property_type', u'room_type',
       u'accommodates', u'bathrooms', u'bedrooms', u'beds', u'bed_type',
       u'amenities', u'square_feet', u'price', u'weekly_price',
       u'monthly_price', u'security_deposit', u'cleaning_fee',
       u'guests_included', u'extra_people', u'minimum_nights',
       u'maximum_nights', u'calendar_updated', u'has_availability',
       u'availability_30', u'availability_60', u'availability_90',
       u'availability_365', u'calendar_last_scraped', u'number_of_reviews',
       u'first_review', u'last_review', u'review_scores_rating',
       u'review_scores_accuracy', u'review_scores_cleanliness',
       u'review_scores_checkin', u'review_scores_communication',
       u'review_scores_location', u'review_scores_value', u'requires_license',
       u'license', u'jurisdiction_names', u'instant_bookable',
       u'cancellation_policy', u'require_guest_profile_picture',
       u'require_guest_phone_verification', u'calculated_host_listings_count',
       u'reviews_per_month'],
      dtype='object')

In [473]:
attributes = [u'id', u'listing_url', u'name', u'host_id',u'host_url', u'host_name', 
              u'host_response_time', u'host_response_rate',u'host_acceptance_rate', u'host_is_superhost',
             u'host_total_listings_count', u'monthly_price', u'minimum_nights',u'number_of_reviews', u'instant_bookable', 
              u'room_type',u'bedrooms']
listings_original = listings_ia2[attributes]

In [474]:
listings_original

,id,listing_url,name,host_id,host_url,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,monthly_price,minimum_nights,number_of_reviews,instant_bookable,room_type,bedrooms
0,1810172,https://www.airbnb.com/rooms/1810172,Room for 2 in Rozzie - Full Bath,8834105,https://www.airbnb.com/users/show/8834105,Rebecca,within an hour,100%,100%,t,2,"$1,300.00",1,15,f,Private room,1
1,6976,https://www.airbnb.com/rooms/6976,Mexican Folk Art Haven in Boston,16701,https://www.airbnb.com/users/show/16701,Phil,within an hour,100%,50%,t,1,"$1,350.00",3,32,f,Private room,1
2,3075044,https://www.airbnb.com/rooms/3075044,Charming room in pet friendly apt,2572247,https://www.airbnb.com/users/show/2572247,Andrea,within a few hours,100%,100%,f,1,NaN,3,20,f,Private room,1
3,4283698,https://www.airbnb.com/rooms/4283698,Private 1 bedroom w/ kitchenette,333210,https://www.airbnb.com/users/show/333210,Gena & Leon,within a few hours,94%,96%,f,1,"$2,300.00",1,25,f,Entire home/apt,1
4,4085362,https://www.airbnb.com/rooms/4085362,"Sub""Urban"" Vacationing Rm 2",3164508,https://www.airbnb.com/users/show/3164508,Marilyn,within a few hours,100%,87%,f,2,NaN,1,12,f,Private room,1
5,225834,https://www.airbnb.com/rooms/225834,Skyline View to Boston,1176995,https://www.airbnb.com/users/show/1176995,Duane,within an hour,100%,100%,t,2,"$1,320.00",1,33,t,Private room,1
6,7252607,https://www.airbnb.com/rooms/7252607,Private Room near Public Transport,34552909,https://www.airbnb.com/users/show/34552909,Barrie,within a day,100%,80%,f,3,NaN,5,2,f,Private room,1
7,1936861,https://www.airbnb.com/rooms/1936861,Private Room in Rozzie,10021116,https://www.airbnb.com/users/show/10021116,Douglas,within an hour,100%,82%,t,1,NaN,1,85,f,Private room,1
8,225979,https://www.airbnb.com/rooms/225979,Cozy Room & Fresh Roasted Coffee,1176995,https://www.airbnb.com/users/show/1176995,Duane,within an hour,100%,100%,t,2,"$1,100.00",1,59,t,Private room,1
9,2583074,https://www.airbnb.com/rooms/2583074,Cozy room in a charming villa.,13226301,https://www.airbnb.com/users/show/13226301,Mohamed,within a few hours,100%,100%,f,2,$800.00,2,17,f,Private room,1
10,6933545,https://www.airbnb.com/rooms/6933545,Cozy Room On the Arnold Arboretum,15472064,https://www.airbnb.com/users/show/15472064,Herb,within a few hours,100%,93%,f,1,"$1,500.00",1,25,f,Private room,1
11,5434353,https://www.airbnb.com/rooms/5434353,Quiet Beauty in Boston,9658771,https://www.airbnb.com/users/show/9658771,Anthony,a few days or more,20%,100%,f,1,"$3,000.00",3,1,f,Entire home/apt,2
12,4025194,https://www.airbnb.com/rooms/4025194,Queen Bed/Near Subway/Free Passes,1480518,https://www.airbnb.com/users/show/1480518,Lisa,within an hour,100%,100%,t,4,NaN,1,91,t,Private room,1
13,1591827,https://www.airbnb.com/rooms/1591827,PrivRoom+Bath In Roslindale/Boston,8491165,https://www.airbnb.com/users/show/8491165,Jeff,within an hour,100%,100%,f,1,NaN,2,105,f,Private room,1
14,753446,https://www.airbnb.com/rooms/753446,6 miles away from downtown Boston!,3962517,https://www.airbnb.com/users/show/3962517,Sami,within an hour,100%,100%,f,1,NaN,1,7,f,Private room,1
15,3755609,https://www.airbnb.com/rooms/3755609,Lovely & Gracious Victorian room,19223882,https://www.airbnb.com/users/show/19223882,Rosa,within a few hours,100%,100%,t,1,"$1,800.00",3,13,f,Private room,1
16,5884429,https://www.airbnb.com/rooms/5884429,"2 Rooms, Private Bath, AC -sleeps 4",15396970,https://www.airbnb.com/users/show/15396970,Linda,within an hour,100%,96%,t,4,NaN,1,9,f,Private room,1
17,879929,https://www.airbnb.com/rooms/879929,Surround yourself with custom art!,4653380,https://www.airbnb.com/users/show/4653380,Beth,within an hour,100%,71%,f,1,"$1,500.00",1,41,f,Private room,1
18,1494726,https://www.airbnb.com/rooms/1494726,Cozy in Rozzie!,7506913,https://www.airbnb.com/users/show/7506913,Maria Cecilia,within an hour,100%,100%,f,2,"$1,499.00",3,6,t,Private room,1
19,7651065,https://www.airbnb.com/rooms/7651065,Come Home to Boston,15396970,https://www.airbnb.com/users/show/15396970,Linda,within an hour,100%,96%,t,4,NaN,1,6,f,Private room,1
20,3420384,https://www.airbnb.com/rooms/3420384,"Convient, Safe and Comfortable",431385,https://www.airbnb.com/users/show/431385,Cynthia,within a few hours,100%,NaN,f,1,NaN,3,0,f,Private room,1
21,8473851,https://www.airbnb.com/rooms/8473851,Private Room in Single Family Home,44625108,https://www.airbnb.com/users/show/44625108,Jessica,within a few hours,100%,80%,f,1,NaN,1,0,f,Private room,1
22,1668313,https://www.airbnb.com/rooms/1668313,Room in Rozzie-Twin Bed-Full Bath,8834105,https://www.airbnb.com/users/show/8834105,Rebecca,within an hour,100%,100%,t,2,"$1,125.00",1,12,f,Private room,1
23,3575220,https://www.airbnb.com/rooms/3575220,The Artist room in beautiful villa.,13226301,https://www.airbnb.com/users/show/13226301,Mohamed,within a few hours,100%,100%,f,2,$950.00,2,7,f,Private room,1
24,4922204,https://www.airbnb.com/rooms/4922204,Charming new house-15 min to Boston,6570877,https://www.airbnb.com/users/show/6570877,Juliet,within a few hours,94%,90%,f,3,NaN,1,39,f,Entire home/apt,3
25,1724900,https://www.airbnb.com/rooms/1724900,Charming sunlit house in Boston,7723912,https://www.airbnb.com/users/show/7723912,Fj,within a day,90%,100%,f,2,"$2,876.00",5,15,f,Entire home/apt,2
26,849408,https://www.airbnb.com/rooms/849408,Perfect & Practical Boston Rental,4434391,https://www.airbnb.com/users/show/4434391,Damon,within an hour,100%,100%,t,2,NaN,4,26,f,Entire home/apt,3
27,5759676,https://www.airbnb.com/rooms/5759676,Perfect home away from home,151823,https://www.airbnb.com/users/show/151823,Phoebe,within a day,100%,NaN,f,1,NaN,4,2,f,Entire home/apt,4
28,3988018,https://www.airbnb.com/rooms/3988018,Sports Room/Near Subway/Free Passes,1480518,https://www.airbnb.com/users/show/1480518,Lisa,within an hour,100%,100%,t,4,NaN,1,101,t,Private room,1
29,6242681,https://www.airbnb.com/rooms/6242681,Rozzie condo with art & Goldens,32407843,https://www.airbnb.com/users/show/32407843,Molly,within a few hours,100%,85%,f,1,NaN,1,18,f,Private room,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2528,8533578,https://www.airbnb.com/rooms/8533578,Gorgeous Brookline/Boston home (#2),30808826,https://www.airbnb.com/users/show/30808826,Sean And Bernadine,within a few hours,100%,100%,f,3,"$9,500.00",2,0,t,Entire home/apt,3
2529,4729833,https://www.airbnb.com/rooms/4729833,"Two-bedroom, 1-bathroom",24424546,https://www.airbnb.com/users/show/24424546,Liliana,within an hour,71%,100%,f,1,"$2,400.00",5,0,f,Entire home/apt,2
2530,7619794,https://www.airbnb.com/rooms/7619794,"Luxurious, spacey studio in Boston!",39536288,https://www.airbnb.com/users/show/39536288,Alex,within an hour,100%,100%,f,4,NaN,1,0,f,Entire home/apt,0
2531,8127009,https://www.airbnb.com/rooms/8127009,Bright appartment-12' from downtown,28389529,https://www.airbnb.com/users/show/28389529,Aurore,within an hour,100%,96%,f,1,NaN,2,5,t,Private room,1
2532,6300161,https://www.airbnb.com/rooms/6300161,Lux Brookline 2BR w/ gym & WiFi,9419684,https://www.airbnb.com/users/show/9419684,Mike,within a few hours,92%,76%,f,206,"$8,070.00",3,0,f,Entire home/apt,2
2533,7332266,https://www.airbnb.com/rooms/7332266,"Sunny private room,Longwood, Fenway",31340713,https://www.airbnb.com/users/show/31340713,Kama,within a few hours,99%,99%,f,5,NaN,2,6,f,Private room,1
2534,6958692,https://www.airbnb.com/rooms/6958692,8min walk to Harvard Square-room 1,36462476,https://www.airbnb.com/users/show/36462476,Nina,within an hour,90%,96%,f,8,NaN,1,7,t,Private room,1
2535,5040534,https://www.airbnb.com/rooms/5040534,Best safe location 1st Floor room 2,25078045,https://www.airbnb.com/users/show/25078045,Edward,within an hour,100%,100%,f,12,"$1,172.00",1,6,f,Private room,1
2536,2083261,https://www.airbnb.com/rooms/2083261,Beautiful Apart in Cambridgeport,10641213,https://www.airbnb.com/users/show/10641213,Sejal,within a day,56%,100%,f,1,"$1,000.00",2,4,f,Private room,1
2537,8516029,https://www.airbnb.com/rooms/8516029,Private apartment close the city!,162722,https://www.airbnb.com/users/show/162722,Lacey,within a day,100%,100%,f,1,"$1,915.00",1,0,f,Entire home/apt,1
2538,6093004,https://www.airbnb.com/rooms/6093004,Private room near T,19246369,https://www.airbnb.com/users/show/19246369,Joe,within an hour,97%,100%,f,16,NaN,1,14,t,Private room,1
2539,4438351,https://www.airbnb.com/rooms/4438351,"skylit suite w/bath, porch, parking",9499646,https://www.airbnb.com/users/show/9499646,Robin,within a few hours,100%,54%,t,1,NaN,2,32,f,Private room,1
2540,7454474,https://www.airbnb.com/rooms/7454474,A room in the village. Room 4,11557910,https://www.airbnb.com/users/show/11557910,Charles,within a few hours,100%,100%,t,5,"$2,250.00",4,1,f,Private room,1
2541,7005442,https://www.airbnb.com/rooms/7005442,Cute 1br apt near Harvard Sq,36720541,https://www.airbnb.com/users/show/36720541,Daniel,NaN,NaN,NaN,f,1,NaN,1,0,f,Entire home/apt,1
2542,2079649,https://www.airbnb.com/rooms/2079649,8/1 nice/quiet Furn 1 bd in 2 bd TH,10625610,https://www.airbnb.com/users/show/10625610,Jesse,within a few hours,86%,100%,f,1,"$1,440.00",5,0,f,Private room,1
2543,5593783,https://www.airbnb.com/rooms/5593783,Quiet cozy room near T,19246369,https://www.airbnb.com/users/show/19246369,Joe,within an hour,97%,100%,f,16,NaN,1,3,t,Private room,1
2544,5470315,https://www.airbnb.com/rooms/5470315,Best safe location 2nd floor room 6,25078045,https://www.airbnb.com/users/show/25078045,Edward,within an hour,100%,100%,f,12,"$1,281.00",4,11,f,Private room,1
2545,3701108,https://www.airbnb.com/rooms/3701108,sunny furnished studio close to T,17576539,https://www.airbnb.com/users/show/17576539,Lushan,within a few hours,100%,100%,f,1,"$2,000.00",1,9,f,Entire home/apt,0
2546,5320198,https://www.airbnb.com/rooms/5320198,"Comfy, rm Harvard Sq w Pvt. Ent/bth",7704595,https://www.airbnb.com/users/show/7704595,Holly,within a day,100%,NaN,f,2,"$1,500.00",6,0,f,Private room,1
2547,6626424,https://www.airbnb.com/rooms/6626424,"Two bed, Perfectly located, updated",6823717,https://www.airbnb.com/users/show/6823717,Juan Carlos,within a few hours,100%,93%,f,3,NaN,3,3,t,Entire home/apt,2
2548,6956835,https://www.airbnb.com/rooms/6956835,8min walk to Harvard Square-Room 4,36462476,https://www.airbnb.com/users/show/36462476,Nina,within an hour,90%,96%,f,8,NaN,1,7,f,Private room,1
2549,7763582,https://www.airbnb.com/rooms/7763582,"5 min walk to Subway, 15 to Harvard",25064382,https://www.airbnb.com/users/show/25064382,Al,within a few hours,96%,87%,f,11,"$1,500.00",14,1,f,Private room,1
2550,5874337,https://www.airbnb.com/rooms/5874337,"Great 1 br, short walk to Harvard",4322960,https://www.airbnb.com/users/show/4322960,William,within a day,60%,90%,f,1,"$3,500.00",2,5,f,Entire home/apt,1
2551,394462,https://www.airbnb.com/rooms/394462,Your pad - 10 Min to Boston center,1866924,https://www.airbnb.com/users/show/1866924,David,within a few hours,100%,100%,f,2,"$1,100.00",2,36,f,Private room,1
2552,3051609,https://www.airbnb.com/rooms/3051609,Female roommate; Close to Harvard,11441054,https://www.airbnb.com/users/show/11441054,Katy,within a few hours,89%,74%,f,2,"$1,095.00",1,5,f,Private room,1
2553,8118800,https://www.airbnb.com/rooms/8118800,Convenient Harvard apartment!,42872576,https://www.airbnb.com/users/show/42872576,Jess,within an hour,100%,100%,f,1,NaN,1,3,t,Entire home/apt,1
2554,6185167,https://www.airbnb.com/rooms/6185167,In the Heart of Brookline,8118445,https://www.airbnb.com/users/show/8118445,Pratap,within an hour,100%,83%,f,2,"$3,950.00",2,19,f,Entire home/apt,2
2555,3448991,https://www.airbnb.com/rooms/3448991,"Double Room, easy access to Boston",17382292,https://www.airbnb.com/users/show/17382292,Sara Ann,within a few hours,100%,90%,t,1,NaN,1,30,f,Private room,1
2556,7968929,https://www.airbnb.com/rooms/7968929,Warm & Spacious 3BR by Flatbook,12243051,https://www.airbnb.com/users/show/12243051,Flatbook,within a few hours,99%,98%,f,222,NaN,3,2,t,Entire home/apt,3
2557,6186360,https://www.airbnb.com/rooms/6186360,Elegant HarvardSQ on Charles River,5161972,https://www.airbnb.com/users/show/5161972,Johanna,within a few hours,100%,73%,f,1,"$5,600.00",1,3,f,Entire home/apt,2

# Calendar related attributes

In [335]:
def parse_calendar(list_calendar):
    date = []
    price_USD = []
    availability = []
    for month in list_calendar['calendar_months']:
        for day in month['days']:
            date.append(day['date'])
            price_USD.append(day['price']['native_price'])
            availability.append(day['available'])
    return pd.DataFrame({'date':date, 'price_USD': price_USD, 'availability':availability})

def find_orphans(cal, length):
    orphan_start = []
    orphan_end = []
    orphan_price = []

    index = 0
    while index < len(cal['availability']) - length:
        count = 0
        start = index
        while cal['availability'][index] == True and count < length:
            count += 1
            if count >= length and cal['availability'][index + 1] == False:
                orphan_start.append(cal['date'][start])
                orphan_end.append(cal['date'][index])
                if length == 1:
                    orphan_price.append(cal['price_USD'][start])
                else:
                    orphan_price.append(np.mean(cal['price_USD'][start: index]))
                break
            index += 1
        index += 1
    if len(orphan_start) > 0:
        return pd.DataFrame({'Start': orphan_start, 'End': orphan_end, 'Price': orphan_price})
    else:
        return []

def listings_price_var(calendars):
    listings_var = {}
    for i in calendars.keys():
        listings_var[i] = np.var(parse_calendar(calendars[i])['price_USD'])
    return listings_var

# Read in calendars

In [481]:
def merge_dicts(*dict_args):
    '''
    Given any number of dicts, shallow copy and merge into a new dict,
    precedence goes to key value pairs in latter dicts.
    '''
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result
cal = pd.read_json('calendars/cal.json')
cal2 = pd.read_json('calendars/cal_2.json')
cal3 = pd.read_json('calendars/cal_3.json')
cal3 = pd.read_json('calendars/cal_3.json')

calendars = merge_dicts(cal,cal2,cal3, cal4)

# Parse Calendars from json

In [482]:
parsed_calendars = {}
for i in calendars.keys():
    parsed_calendars[i] = parse_calendar(calendars[i])

# df_calendar: extract all calendar related features

In [483]:
id = [int(i) for i in parsed_calendars.keys()]

In [484]:
df_calendar = pd.DataFrame({'id': id, 'calendars': parsed_calendars.values()})

In [485]:
def cal_occupancy(availability, length):
    return np.mean(availability[:length])

In [486]:
cal_occupancy(parsed_calendars.values()[10]['availability'], 30)

0.96666666666666667

## Calculate occupancy

In [487]:
df_calendar['occupancy_1m'] = [cal_occupancy(i['availability'], 30) for i in parsed_calendars.values()]
df_calendar['occupancy_3m'] = [cal_occupancy(i['availability'], 90) for i in parsed_calendars.values()]

## Calculate orphan's day

In [346]:
df_calendar['orphan_1d'] = [find_orphans(i, 1) for i in parsed_calendars.values()]
df_calendar['orphan_2d'] = [find_orphans(i, 2) for i in parsed_calendars.values()]
df_calendar['orphan_3d'] = [find_orphans(i, 3) for i in parsed_calendars.values()]
df_calendar['orphan_4d'] = [find_orphans(i, 4) for i in parsed_calendars.values()]
df_calendar['orphan_5d'] = [find_orphans(i, 5) for i in parsed_calendars.values()]
df_calendar['orphan_6d'] = [find_orphans(i, 6) for i in parsed_calendars.values()]
df_calendar['num_orphan_1d'] = [len(i) for i in df_calendar['orphan_1d']]
df_calendar['num_orphan_2d'] = [len(i) for i in df_calendar['orphan_2d']]
df_calendar['num_orphan_3d'] = [len(i) for i in df_calendar['orphan_3d']]
df_calendar['num_orphan_4d'] = [len(i) for i in df_calendar['orphan_4d']]
df_calendar['num_orphan_5d'] = [len(i) for i in df_calendar['orphan_5d']]
df_calendar['num_orphan_6d'] = [len(i) for i in df_calendar['orphan_6d']]

## Calculate Price Variance

In [347]:
df_calendar['prics_std'] = [np.std(i['price_USD']) for i in parsed_calendars.values()]

In [348]:
df_calendar

,calendars,id,occupancy_1m,occupancy_3m,orphan_1d,orphan_2d,orphan_3d,orphan_4d,orphan_5d,orphan_6d,num_orphan_1d,num_orphan_2d,num_orphan_3d,num_orphan_4d,num_orphan_5d,num_orphan_6d,prics_std
0,availability date price_USD 0 ...,6725634,0.133333,0.044444,[],[],[],End Price Start 0 2016-0...,[],[],0,0,0,1,0,0,16.065213
1,availability date price_USD 0 ...,4964365,0.366667,0.122222,End Price Start 0 2016-03-19...,End Price Start 0 2016-03-19...,End Price Start 0 2016-03-19...,[],End Price Start 0 2016-03-19...,[],1,1,1,0,1,0,10.270712
2,availability date price_USD 0 ...,5724845,0.000000,0.000000,End Price Start 0 2016-06-01...,[],[],[],[],[],1,0,0,0,0,0,13.552619
3,availability date price_USD 0 ...,8339473,0.000000,0.011111,End Price Start 0 2016-04-19...,[],[],[],[],[],1,0,0,0,0,0,10.647943
4,availability date price_USD 0 ...,2023445,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
5,availability date price_USD 0 ...,7929879,0.866667,0.822222,End Price Start 0 2016-04-03...,End Price Start 0 2016-04-22...,[],End Price Start 0 2016-...,End Price Start 0 2016-04-22...,End Price Start 0 2016-03-04...,3,1,0,2,1,1,36.361588
6,availability date price_USD 0 ...,7225376,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
7,availability date price_USD 0 ...,5726250,0.466667,0.722222,End Price Start 0 2016-03-31...,End Price Start 0 2016-02-29...,End Price Start 0 2016-03-31...,End Price Start 0 2016-04-07...,End Price Start 0 2016-03-31...,[],3,2,2,2,1,0,24.494897
8,availability date price_USD 0 ...,6758443,0.033333,0.533333,End Price Start 0 2016-03-26...,[],[],[],[],[],1,0,0,0,0,0,23.523713
9,availability date price_USD 0 ...,7446573,0.000000,0.300000,End Price Start 0 2016-04-29...,[],End Price Start 0 2016-04-29...,[],[],End Price Start 0 2016-04-29...,1,0,1,0,0,1,69.146147
10,availability date price_USD 0 ...,4890682,0.966667,0.988889,[],End Price Start 0 2016-03-06...,[],[],[],[],0,1,0,0,0,0,11.293849
11,availability date price_USD 0 ...,1523772,0.000000,0.322222,[],[],[],[],[],[],0,0,0,0,0,0,13.552619
12,availability date price_USD 0 ...,6758462,0.066667,0.300000,[],End Price Start 0 2016-02-29...,[],[],[],[],0,1,0,0,0,0,1.777001
13,availability date price_USD 0 ...,8536127,0.933333,0.755556,End Price Start 0 2016-03-30...,End Price Start 0 2016-03-18...,End Price Start 0 2016-05-11...,End Price Start 0 2016-05-18...,End Price Start 0 2016-03-30...,End Price Start 0 2016-03-18...,2,3,1,2,2,2,0.000000
14,availability date price_USD 0 ...,6692941,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
15,availability date price_USD 0 ...,2473997,1.000000,1.000000,[],[],[],[],[],[],0,0,0,0,0,0,4.517540
16,availability date price_USD 0 ...,7856208,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
17,availability date price_USD 0 ...,6758482,0.566667,0.855556,[],[],[],[],[],[],0,0,0,0,0,0,20.192327
18,availability date price_USD 0 ...,4610745,0.100000,0.033333,End Price Start 0 2016-02-28...,End Price Start 0 2016-03-05...,[],[],[],[],1,1,0,0,0,0,10.612105
19,availability date price_USD 0 ...,4759640,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,85.833251
20,availability date price_USD 0 ...,213086,0.766667,0.922222,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
21,availability date price_USD 0 ...,163941,0.400000,0.411111,End Price Start 0 2016-03-09...,End Price Start 0 2016-03-21...,End Price Start 0 2016-03-09...,End Price Start 0 2016-...,[],End Price Start 0 2016-04-07...,6,2,5,2,0,1,79.367857
22,availability date price_USD 0 ...,508017,0.100000,0.300000,End Price Start 0 2016-03-06...,End Price Start 0 2016-03-02...,End Price Start 0 2016-05-11...,End Price Start 0 2016-...,End Price Start 0 2016-05-05...,[],3,3,1,2,1,0,38.506918
23,availability date price_USD 0 ...,7708787,0.866667,0.777778,End Price Start 0 2016-03-15...,End Price Start 0 2016-03-15...,End Price Start 0 2016-04-29...,[],End Price Start 0 2016-03-15...,End Price Start 0 2016-04-09...,4,3,1,0,3,3,29.014423
24,availability date price_USD 0 ...,4604023,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,0.000000
25,availability date price_USD 0 ...,1171578,1.000000,1.000000,[],[],[],[],[],[],0,0,0,0,0,0,16.226056
26,availability date price_USD 0 ...,7880828,0.033333,0.477778,End Price Start 0 2016-03-20...,End Price Start 0 2016-04-13...,End Price Start 0 2016-04-13...,[],End Price Start 0 2016-04-13...,[],3,1,1,0,1,0,2.999259
27,availability date price_USD 0 ...,7741566,0.433333,0.711111,End Price Start 0 2016-03-15...,End Price Start 0 2016-05-23...,End Price Start 0 2016-03-15...,[],[],[],3,1,3,0,0,0,16.075118
28,availability date price_USD 0 ...,6725762,0.200000,0.133333,End Price Start 0 2016-03-02...,End Price Start 0 2016-03-29...,End Price Start 0 2016-03-09...,[],[],[],4,2,2,0,0,0,14.352498
29,availability date price_USD 0 ...,5054601,0.400000,0.633333,End Price Start 0 2016-03-31...,End Price Start 0 2016-03-31...,End Price Start 0 2016-04-15...,End Price Start 0 2016-03-31...,End Price Start 0 2016-03-31...,End Price Start 0 2016-03-18...,6,1,2,1,1,1,6.034925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,availability date price_USD 0 ...,6930296,0.266667,0.711111,End Price Start 0 2016-03-31...,End Price Start 0 2016-03-31...,End Price Start 0 2016-03-31...,[],End Price Start 0 2016-03-31...,[],2,2,1,0,2,0,168.401057
1940,availability date price_USD 0 ...,2555771,0.933333,0.977778,[],End Price Start 0 2016-03-06...,[],[],[],[],0,1,0,0,0,0,0.000000
1941,availability date price_USD 0 ...,8576895,0.000000,0.033333,End Price Start 0 2016-05-10...,[],End Price Start 0 2016-05-10...,[],[],[],1,0,1,0,0,0,0.000000
1942,availability date price_USD 0 ...,1811776,0.200000,0.166667,End Price Start 0 2016-03-20...,End Price Start 0 2016-03-02...,End Price Start 0 2016-04-07...,End Price Start 0 2016-03-30...,[],[],3,1,1,2,0,0,35.810790
1943,availability date price_USD 0 ...,2875267,0.533333,0.344444,End Price Start 0 2016-03-16...,End Price Start 0 2016-03-01...,End Price Start 0 2016-03-16...,End Price Start 0 2016-04-28...,End Price Start 0 2016-03-16...,[],4,5,1,4,2,0,9.976844
1944,availability date price_USD 0 ...,2441095,0.833333,0.844444,End Price Start 0 2016-04-20...,End Price Start 0 2016-02-29...,[],[],[],[],1,1,0,0,0,0,29.449369
1945,availability date price_USD 0 ...,8052617,0.500000,0.655556,End Price Start 0 2016-03-22...,[],End Price Start 0 2016-03-22...,End Price Start 0 2016-03-16...,[],End Price Start 0 2016-03-04...,3,0,3,5,0,1,71.025297
1946,availability date price_USD 0 ...,7757707,0.300000,0.266667,End Price Start 0 2016-03-01...,End Price Start 0 2016-03-25...,End Price Start 0 2016-03-01...,End Price Start 0 2016-03-14...,[],[],2,1,2,1,0,0,67.350226
1947,availability date price_USD 0 ...,6676364,0.100000,0.211111,End Price Start 0 2016-03-23...,End Price Start 0 2016-05-14...,End Price Start 0 2016-03-29...,End Price Start 0 2016-05-25...,End Price Start 0 2016-05-14...,End Price Start 0 2016-06-03...,9,1,3,1,1,1,2.852123
1948,availability date price_USD 0 ...,1884045,0.900000,0.800000,End Price Start 0 2016-03-03...,End Price Start 0 2016-03-03...,[],[],End Price Start 0 2016-03-03...,[],1,2,0,0,1,0,0.000000
1949,availability date price_USD 0 ...,8552338,0.033333,0.011111,End Price Start 0 2016-02-28...,[],[],[],[],[],1,0,0,0,0,0,4.573412
1950,availability date price_USD 0 ...,6823828,0.266667,0.566667,End Price Start 0 2016-03-06...,End Price Start 0 2016-03-25...,[],End Price Start 0 2016-03-02...,[],End Price Start 0 2016-05-22...,6,1,0,3,0,1,80.674309
1951,availability date price_USD 0 ...,3571617,0.400000,0.555556,End Price Start 0 2016-03-24...,End Price Start 0 2016-04-25...,End Price Start 0 2016-03-30...,End Price Start 0 2016-...,End Price Start 0 2016-04-25...,End Price Start 0 2016-03-04...,4,1,2,2,1,1,38.405777
1952,availability date price_USD 0 ...,3375010,0.366667,0.377778,End Price Start 0 2016-03-03...,End Price Start 0 2016-02-29...,End Price Start 0 2016-04-26...,End Price Start 0 2016-04-07...,End Price Start 0 2016-03-1...,[],6,5,1,2,2,0,13.909816
1953,availability date price_USD 0 ...,6848424,0.400000,0.322222,End Price Start 0 2016-03-...,End Price Start 0 2016-03-03...,End Price Start 0 2016-03-20...,[],End Price Start 0 2016-03-03...,[],12,1,9,0,1,0,42.268626
1954,availability date price_USD 0 ...,2326445,0.166667,0.322222,End Price Start 0 2016-03-23...,End Price Start 0 2016-05-04...,End Price Start 0 2016-03-23...,[],End Price Start 0 2016-05-04...,End Price Start 0 2016-05-30...,5,2,5,0,1,1,12.154896
1955,availability date price_USD 0 ...,3250847,0.733333,0.911111,End Price Start 0 2016-03-06...,[],[],[],[],[],1,0,0,0,0,0,0.000000
1956,availability date price_USD 0 ...,8552387,0.000000,0.055556,End Price Start 0 2016-04-18...,End Price Start 0 2016-04-18...,[],[],End Price Start 0 2016-04-18...,[],1,1,0,0,1,0,37.054841
1957,availability date price_USD 0 ...,5267396,0.600000,0.744444,End Price Start 0 2016-03-15...,End Price Start 0 2016-03-30...,End Price Start 0 2016-03-30...,End Price Start 0 2016-03-15...,End Price Start 0 2016-03-3...,[],3,2,2,2,2,0,29.630872
1958,availability date price_USD 0 ...,311240,0.466667,0.655556,End Price Start 0 2016-03-02...,End Price Start 0 2016-03-28...,End Price Start 0 2016-04-13...,End Price Start 0 2016-...,End Price Start 0 2016-04-13...,[],3,3,1,2,1,0,65.610408
1959,availability date price_USD 0 ...,4461901,1.000000,1.000000,[],[],[],[],[],[],0,0,0,0,0,0,20.231091
1960,availability date price_USD 0 ...,6741968,0.000000,0.333333,End Price Start 0 2016-04-15...,End Price Start 0 2016-04-15...,End Price Start 0 2016-04-21...,[],End Price Start 0 2016-04-15...,[],4,4,2,0,3,0,30.756532
1961,availability date price_USD 0 ...,3629014,0.000000,0.000000,[],[],[],[],[],[],0,0,0,0,0,0,7.376533
1962,availability date price_USD 0 ...,3129309,0.000000,0.333333,End Price Start 0 2016-04-08...,End Price Start 0 2016-04-05...,[],[],End Price Start 0 2016-04-15...,End Price Start 0 2016-05-14...,4,4,0,0,2,1,25.690289
1963,availability date price_USD 0 ...,8519646,0.966667,0.922222,[],End Price Start 0 2016-04-26...,[],[],[],End Price Start 0 2016-03-04...,0,1,0,0,0,1,21.465822
1964,availability date price_USD 0 ...,5521378,1.000000,1.000000,[],[],[],[],[],[],0,0,0,0,0,0,5.872801
1965,availability date price_USD 0 ...,7921649,0.133333,0.355556,End Price Start 0 2016-05-31...,[],End Price Start 0 2016-05-31...,End Price Start 0 2016-0...,[],[],1,0,1,2,0,0,21.001617
1966,availability date price_USD 0 ...,4997112,0.466667,0.500000,End Price Start 0 2016-03-15...,End Price Start 0 2016-03-26...,[],End Price Start 0 2016-03-15...,End Price Start 0 2016-03-26...,[],3,3,0,1,2,0,31.453301
1967,availability date price_USD 0 ...,1992020,0.366667,0.300000,End Price Start 0 2016-03-20...,End Price Start 0 2016-03-11...,End Price Start 0 2016-04-21...,[],[],End Price Start 0 2016-03-04...,5,4,2,0,0,2,0.000000
1968,availability date price_USD 0 ...,7356415,1.000000,0.611111,End Price Start 0 2016-04-15...,[],End Price Start 0 2016-04-15...,[],[],End Price Start 0 2016-04-15...,1,0,1,0,0,1,0.000000

# Check orphans' data

In [492]:
find_orphans(parsed_calendars[ids_with_cal[0]], 5)

          End  Price       Start
0  2016-05-19    269  2016-05-15

In [493]:
parsed_calendars[ids_with_cal[0]]

    availability        date  price_USD
0          False  2016-02-28        199
1          False  2016-02-29        199
2          False  2016-03-01        199
3          False  2016-03-02        199
4          False  2016-03-03        199
5          False  2016-03-04        199
6          False  2016-03-05        199
7          False  2016-03-06        199
8          False  2016-03-07        199
9          False  2016-03-08        199
10         False  2016-03-09        199
11         False  2016-03-10        199
12         False  2016-03-11        199
13         False  2016-03-12        199
14         False  2016-03-13        199
15         False  2016-03-14        199
16         False  2016-03-15        269
17         False  2016-03-16        269
18         False  2016-03-17        269
19         False  2016-03-18        269
20         False  2016-03-19        269
21          True  2016-03-20        269
22          True  2016-03-21        269
23         False  2016-03-22        269
24         False  2016-03-23        269
25         False  2016-03-24        269
26         False  2016-03-25        269
27         False  2016-03-26        199
28         False  2016-03-27        199
29         False  2016-03-28        199
..           ...         ...        ...
75         False  2016-05-06        269
76         False  2016-05-07        269
77         False  2016-05-08        269
78         False  2016-05-09        269
79          True  2016-05-10        269
80          True  2016-05-11        269
81         False  2016-05-12        269
82         False  2016-05-13        269
83         False  2016-05-14        269
84          True  2016-05-15        269
85          True  2016-05-16        269
86          True  2016-05-17        269
87          True  2016-05-18        269
88          True  2016-05-19        269
89         False  2016-05-20        269
90         False  2016-05-21        269
91         False  2016-05-22        269
92         False  2016-05-23        269
93          True  2016-05-24        269
94         False  2016-05-25        269
95         False  2016-05-26        269
96         False  2016-05-27        269
97          True  2016-05-28        269
98          True  2016-05-29        269
99          True  2016-05-30        269
100         True  2016-05-31        269
101         True  2016-06-01        269
102         True  2016-06-02        269
103         True  2016-06-03        269
104         True  2016-06-04        269

[105 rows x 3 columns]

# (Discarded) Combine listings and calendars

In [355]:
listings = pd.merge(df_calendar, listings, on='id', how='inner')

In [356]:
listings.to_json('listings.json')

In [357]:
listings.columns

Index([u'calendars', u'id', u'occupancy_1m', u'occupancy_3m', u'orphan_1d',
       u'orphan_2d', u'orphan_3d', u'orphan_4d', u'orphan_5d', u'orphan_6d',
       u'num_orphan_1d', u'num_orphan_2d', u'num_orphan_3d', u'num_orphan_4d',
       u'num_orphan_5d', u'num_orphan_6d', u'prics_std', u'listing_url',
       u'name', u'host_id', u'host_url', u'host_name', u'host_response_time',
       u'host_response_rate', u'host_acceptance_rate', u'host_is_superhost',
       u'host_total_listings_count', u'monthly_price', u'minimum_nights',
       u'number_of_reviews', u'instant_bookable', u'room_type'],
      dtype='object')

In [495]:
listings.columns

Index([u'id', u'listing_url', u'name', u'host_id', u'host_url', u'host_name',
       u'host_response_time', u'host_response_rate', u'host_acceptance_rate',
       u'host_is_superhost', u'host_total_listings_count', u'monthly_price',
       u'minimum_nights', u'number_of_reviews', u'instant_bookable',
       u'room_type'],
      dtype='object')

# Selecting Listings

In [496]:
import datetime
def days_in_advance(date):
    date = datetime.datetime.strptime(date, '%Y-%m-%d')
    days_in_advance = (date - datetime.datetime.today()).days
    return days_in_advance

In [497]:
'''
differnce between this and find_orphans(cal, length):
Incooperate all necessary infomation for assiging to different buckets

'''

def find_orphans_2(length, listing_id, parsed_calendars = parsed_calendars, listings = listings):
    cal = parsed_calendars[listing_id]
    orphan_start = []
    orphan_end = []
    orphan_price = []

    index = 0
    while index < len(cal['availability']) - length:
        count = 0
        start = index
        while cal['availability'][index] == True and count < length:
            count += 1
            if count >= length and cal['availability'][index + 1] == False:
                orphan_start.append(cal['date'][start])
                orphan_end.append(cal['date'][index])
                if length == 1:
                    orphan_price.append(cal['price_USD'][start])
                else:
                    orphan_price.append(np.mean(cal['price_USD'][start: index]))
                break
            index += 1
        index += 1
    if len(orphan_start) > 0:
        host_id = listings['host_id'][listings['id'] == listing_id].tolist() * len(orphan_start)
        days_advance = [days_in_advance(date) for date in orphan_start]
        return pd.DataFrame({'host_id' : host_id,'listing_id': listing_id, 'Start': orphan_start, 
                             'End': orphan_end, 'Price': orphan_price, 'days_advance': days_advance})
    else:
        return []

In [530]:
def orphan_bucket(orphan_bucket_num, listings = listings):
    orphan_bucket = []
    for i in range(1, orphan_bucket_num + 1):
        orphan_list = []
        for id in parsed_calendars.keys():
            # Whether the length satisfys the listing's minimun nights
            if i >= listings[listings['id'] == id]['minimum_nights'].to_dict().values()[0]:
                orphan = find_orphans_2(i, id)
                if len(orphan) > 0:
                    orphan_list.append(orphan)

        orphan_df = pd.concat(orphan_list)
        orphan_bucket.append(orphan_df)
    return orphan_bucket

In [523]:
listings['id'][0]

1810172

In [517]:
a = listings[listings['id'] == 1810172]['minimum_nights']

In [527]:
a.to_dict().values()[0]

1

In [532]:
for i in range(4,7):
    orphan_list = []
    for id in parsed_calendars.keys():
        orphan = find_orphans_2(i, id)
        if len(orphan) > 0:
            orphan_list.append(orphan)

    orphan_more = pd.concat(orphan_list)

In [531]:
temp = orphan_bucket(3)

In [533]:
orphan_1d = temp[0]
orphan_2d = temp[1]
orphan_3d = temp[2]

In [534]:
orphan_more

           End  Price       Start  days_advance   host_id  listing_id
0   2016-03-04  100.0  2016-02-28           -12   1444340     7929879
0   2016-04-29  199.0  2016-04-24            44  11541727     7446573
0   2016-03-18  250.0  2016-03-13             2  39459066     8536127
1   2016-04-29  250.0  2016-04-24            44  39459066     8536127
0   2016-04-07  229.0  2016-04-02            22      8229      163941
0   2016-04-09  175.0  2016-04-04            24  16671525     7708787
1   2016-04-16  225.0  2016-04-11            31  16671525     7708787
2   2016-05-15  175.0  2016-05-10            60  16671525     7708787
0   2016-03-18   63.8  2016-03-13             2  26098645     5054601
0   2016-06-02  184.4  2016-05-28            78  12243051     7856323
0   2016-03-18  120.0  2016-03-13             2  19036819     3727560
1   2016-03-28  112.0  2016-03-23            12  19036819     3727560
0   2016-04-15  222.2  2016-04-10            30    814298     5791960
0   2016-04-01  125.0  2016-03-27            16   3274255      663770
1   2016-04-01  125.0  2016-03-27            16   3274255      663770
0   2016-04-15  169.0  2016-04-10            30  45402419     8634599
0   2016-04-15  199.0  2016-04-10            30  13124709     6881541
1   2016-06-01  209.4  2016-05-27            77  13124709     6881541
0   2016-03-10  120.0  2016-03-05            -6  19907707     3858697
0   2016-04-12   65.2  2016-04-07            27   8892809     7528746
1   2016-05-01   66.0  2016-04-26            46   8892809     7528746
0   2016-05-29  158.2  2016-05-24            74   2594165     5153080
0   2016-04-10   59.4  2016-04-05            25    635157     6725993
0   2016-03-30  160.0  2016-03-25            14  27015747     5734770
0   2016-03-04   54.0  2016-02-28           -12   6331373     4080000
0   2016-03-18   55.0  2016-03-13             2  12221171     2392462
0   2016-03-04  163.2  2016-02-28           -12  13124709     6160803
0   2016-03-04   85.0  2016-02-28           -12  31340713     7332266
0   2016-04-14   65.0  2016-04-09            29    212445     6709682
0   2016-03-04  179.0  2016-02-28           -12    261895     2564544
..         ...    ...         ...           ...       ...         ...
0   2016-03-25   55.0  2016-03-20             9   5009446     7986820
0   2016-04-24  179.0  2016-04-19            39   4061992     7585431
0   2016-03-25   80.0  2016-03-20             9    174986       40601
0   2016-04-09  144.0  2016-04-04            24  10136526     6614984
0   2016-05-23  268.0  2016-05-18            68  42431392     8036024
0   2016-04-15   79.0  2016-04-10            30  15396970     7651065
0   2016-04-18  345.0  2016-04-13            33   1922657     3342094
0   2016-03-13  450.0  2016-03-08            -3  21609039     5088560
0   2016-03-26  165.0  2016-03-21            10    319393       65329
0   2016-03-18   98.0  2016-03-13             2   2656376      540470
0   2016-05-01  180.0  2016-04-26            46   4746775      892738
0   2016-04-15  230.0  2016-04-10            30    319393       65353
1   2016-04-25  230.0  2016-04-20            40    319393       65353
2   2016-05-10  230.0  2016-05-05            55    319393       65353
0   2016-05-05  210.0  2016-04-30            50    319393       65363
0   2016-04-01   80.0  2016-03-27            16  36453929     6954861
1   2016-04-01   80.0  2016-03-27            16  36453929     6954861
2   2016-04-15   90.0  2016-04-10            30  36453929     6954861
0   2016-03-13  195.0  2016-03-08            -3  17512521     7757680
1   2016-06-01  299.0  2016-05-27            77  17512521     7757680
0   2016-03-04  190.4  2016-02-28           -12  21184200     8052617
0   2016-06-03   84.0  2016-05-29            79  13382900     6676364
0   2016-05-22  350.0  2016-05-17            67  35742537     6823828
0   2016-03-04  167.0  2016-02-28           -12  17984084     3571617
0   2016-05-30  210.0  2016-05-25            75    912631     2326445
0   2016-05-14  171.0  2016-05-09            59   3637081     3129309
0   2016-03-04   80.0  2016-02-28           -12  15098486     8519646
0   2016-03-04   75.0  2016-02-28           -12   6748461     1992020
1   2016-05-03   75.0  2016-04-28            48   6748461     1992020
0   2016-04-15  325.0  2016-04-10            30    914630     7356415

[538 rows x 6 columns]

In [544]:
orphan_1d_advance_1w = orphan_1d[(orphan_1d['days_advance'] > 0) & (orphan_1d['days_advance'] <= 7)]
orphan_1d_advance_2w = orphan_1d[(orphan_1d['days_advance'] > 7) & (orphan_1d['days_advance'] < 14)]
orphan_1d_advance_more = orphan_1d[orphan_1d['days_advance'] > 14]

orphan_2d_advance_1w = orphan_2d[(orphan_2d['days_advance'] > 0) & (orphan_2d['days_advance'] <= 7)]
orphan_2d_advance_2w = orphan_2d[(orphan_2d['days_advance'] > 7) & (orphan_2d['days_advance'] < 14)]
orphan_2d_advance_more = orphan_2d[orphan_2d['days_advance'] > 14]

orphan_3d_advance_1w = orphan_3d[(orphan_3d['days_advance'] > 0) & (orphan_3d['days_advance'] <= 7)]
orphan_3d_advance_2w = orphan_3d[(orphan_3d['days_advance'] > 7) & (orphan_3d['days_advance'] < 14)]
orphan_3d_advance_more = orphan_3d[orphan_3d['days_advance'] > 14]

orphan_more_advance_1w = orphan_more[(orphan_more['days_advance'] > 0) & (orphan_more['days_advance'] <= 7)]
orphan_more_advance_2w = orphan_more[(orphan_more['days_advance'] > 7) & (orphan_more['days_advance'] < 14)]
orphan_more_advance_more = orphan_more[orphan_more['days_advance'] > 14]

# Select Mailing List in each bucket with unique host id

In [545]:
mailing_repo = {'orphan_1d_advance_1w':orphan_1d_advance_1w, 'orphan_1d_advance_2w':orphan_1d_advance_2w, 
                    'orphan_1d_advance_more': orphan_1d_advance_more, 'orphan_2d_advance_1w':orphan_2d_advance_1w, 
                    'orphan_2d_advance_2w':orphan_2d_advance_2w, 'orphan_2d_advance_more': orphan_2d_advance_more,
                    'orphan_3d_advance_1w':orphan_3d_advance_1w, 'orphan_3d_advance_2w':orphan_3d_advance_2w, 
                    'orphan_1d_advance_more':orphan_1d_advance_more, 'orphan_more_advance_1w':orphan_more_advance_1w,
                    'orphan_more_advance_2w' : orphan_more_advance_2w,'orphan_more_advance_more':orphan_more_advance_more}

In [546]:
mailing_repo['orphan_1d_advance_1w']

           End  Price       Start  days_advance   host_id  listing_id
0   2016-03-15    175  2016-03-15             4  16671525     7708787
0   2016-03-16    135  2016-03-16             5   4298040     6643926
0   2016-03-12    195  2016-03-12             1   3462813     2998554
1   2016-03-13     60  2016-03-13             2   8892809     7528746
0   2016-03-13    159  2016-03-13             2   5578043     1220971
0   2016-03-13     41  2016-03-13             2   1407005     1178162
0   2016-03-13    179  2016-03-13             2    261895     2564544
0   2016-03-17     65  2016-03-17             6     68870       57800
0   2016-03-15    280  2016-03-15             4  13822322     2769450
0   2016-03-16     59  2016-03-16             5   9508341     7692933
0   2016-03-17    150  2016-03-17             6  34584706     6609546
0   2016-03-15    151  2016-03-15             4   1369968     3302294
0   2016-03-18     69  2016-03-18             7  15723690     8627123
0   2016-03-14    139  2016-03-14             3  38188681     7472068
1   2016-03-15     55  2016-03-15             4  28184994     7693354
1   2016-03-13     75  2016-03-13             2   4104737     3089505
0   2016-03-18     90  2016-03-18             7   3637081     1615033
0   2016-03-16     55  2016-03-16             5  19782214     6645010
2   2016-03-15     88  2016-03-15             4  23208278     6006121
2   2016-03-13    175  2016-03-13             2  11792930     6596242
0   2016-03-16    249  2016-03-16             5   1444340     1550047
0   2016-03-15    150  2016-03-15             4  28525504     6432655
0   2016-03-15    179  2016-03-15             4   5578043     4573238
0   2016-03-14     54  2016-03-14             3   3474193      682093
1   2016-03-17    271  2016-03-17             6  26704689     5163162
2   2016-03-17    197  2016-03-17             6  28583327     8210702
1   2016-03-14    179  2016-03-14             3  16779145     4065578
0   2016-03-18    265  2016-03-18             7  17783651     4090224
0   2016-03-13     33  2016-03-13             2   6608084     1321422
1   2016-03-15     33  2016-03-15             4   6608084     1321422
..         ...    ...         ...           ...       ...         ...
0   2016-03-16     75  2016-03-16             5   1480518     3987926
0   2016-03-17     62  2016-03-17             6   1407005     1178106
0   2016-03-14     70  2016-03-14             3   1480518     3988018
1   2016-03-12     69  2016-03-12             1  32373289     6240901
0   2016-03-12    155  2016-03-12             1  31993940     6167184
2   2016-03-15    100  2016-03-15             4   9653086     4364989
1   2016-03-17     60  2016-03-17             6   9663343     1850260
0   2016-03-16    169  2016-03-16             5  12243051     7920541
1   2016-03-17    250  2016-03-17             6  10393465     2022303
0   2016-03-12    212  2016-03-12             1   1444340     1175376
1   2016-03-16    154  2016-03-16             5   1444340     1175376
1   2016-03-15    125  2016-03-15             4  20582119     6552654
2   2016-03-17    205  2016-03-17             6  20582119     6134867
0   2016-03-17     54  2016-03-17             6  19246369     3759239
2   2016-03-13     50  2016-03-13             2    204485     7634067
1   2016-03-13     90  2016-03-13             2  10850877     4553903
0   2016-03-18    175  2016-03-18             7  19357187     3890373
2   2016-03-16     89  2016-03-16             5  25742899     7281884
1   2016-03-18    129  2016-03-18             7  25499738     4996375
0   2016-03-16    110  2016-03-16             5    333210     4283698
2   2016-03-18     59  2016-03-18             7  15154687     5446995
1   2016-03-13    189  2016-03-13             2   1461240     1088876
0   2016-03-15    130  2016-03-15             4  24584716     6602217
1   2016-03-18    129  2016-03-18             7  25499738     4947526
1   2016-03-12     55  2016-03-12             1   5009446     7986820
3   2016-03-14     70  2016-03-14             3  42431392     8036024
0   2016-03-15    140  2016-03-15             4   4195134     6823628
0   2016-03-12    125  2016-03-12             1  27849429     8445701
2   2016-03-15    165  2016-03-15             4    319393       65329
0   2016-03-15     98  2016-03-15             4   8993560     4997112

[131 rows x 6 columns]

In [397]:
sorted_repo = sorted(mailing_repo.values(), key = lambda x: len(x))

# New Calendar

In [553]:
mailing_repo = {'orphan_1d_advance_1w':orphan_1d_advance_1w.drop_duplicates(subset='listing_id'), 
                'orphan_1d_advance_2w':orphan_1d_advance_2w.drop_duplicates(subset='listing_id'), 
                    'orphan_1d_advance_more': orphan_1d_advance_more.drop_duplicates(subset='listing_id'), 
                    'orphan_2d_advance_1w':orphan_2d_advance_1w.drop_duplicates(subset='listing_id'), 
                    'orphan_2d_advance_2w':orphan_2d_advance_2w.drop_duplicates(subset='listing_id'),
                    'orphan_2d_advance_more': orphan_2d_advance_more.drop_duplicates(subset='listing_id'),
                    'orphan_3d_advance_1w':orphan_3d_advance_1w.drop_duplicates(subset='listing_id'), 
                    'orphan_3d_advance_2w':orphan_3d_advance_2w.drop_duplicates(subset='listing_id'), 
                    'orphan_3d_advance_more':orphan_1d_advance_more.drop_duplicates(subset='listing_id'), 
                    'orphan_more_advance_1w':orphan_more_advance_1w.drop_duplicates(subset='listing_id'),
                    'orphan_more_advance_2w' : orphan_more_advance_2w.drop_duplicates(subset='listing_id'),
                    'orphan_more_advance_more':orphan_more_advance_more.drop_duplicates(subset='listing_id')}

In [554]:
mailing_repo['orphan_1d_advance_1w']

           End  Price       Start  days_advance   host_id  listing_id
0   2016-03-15    175  2016-03-15             4  16671525     7708787
0   2016-03-16    135  2016-03-16             5   4298040     6643926
0   2016-03-12    195  2016-03-12             1   3462813     2998554
1   2016-03-13     60  2016-03-13             2   8892809     7528746
0   2016-03-13    159  2016-03-13             2   5578043     1220971
0   2016-03-13     41  2016-03-13             2   1407005     1178162
0   2016-03-13    179  2016-03-13             2    261895     2564544
0   2016-03-17     65  2016-03-17             6     68870       57800
0   2016-03-15    280  2016-03-15             4  13822322     2769450
0   2016-03-16     59  2016-03-16             5   9508341     7692933
0   2016-03-17    150  2016-03-17             6  34584706     6609546
0   2016-03-15    151  2016-03-15             4   1369968     3302294
0   2016-03-18     69  2016-03-18             7  15723690     8627123
0   2016-03-14    139  2016-03-14             3  38188681     7472068
1   2016-03-15     55  2016-03-15             4  28184994     7693354
1   2016-03-13     75  2016-03-13             2   4104737     3089505
0   2016-03-18     90  2016-03-18             7   3637081     1615033
0   2016-03-16     55  2016-03-16             5  19782214     6645010
2   2016-03-15     88  2016-03-15             4  23208278     6006121
2   2016-03-13    175  2016-03-13             2  11792930     6596242
0   2016-03-16    249  2016-03-16             5   1444340     1550047
0   2016-03-15    150  2016-03-15             4  28525504     6432655
0   2016-03-15    179  2016-03-15             4   5578043     4573238
0   2016-03-14     54  2016-03-14             3   3474193      682093
1   2016-03-17    271  2016-03-17             6  26704689     5163162
2   2016-03-17    197  2016-03-17             6  28583327     8210702
1   2016-03-14    179  2016-03-14             3  16779145     4065578
0   2016-03-18    265  2016-03-18             7  17783651     4090224
0   2016-03-13     33  2016-03-13             2   6608084     1321422
0   2016-03-13     90  2016-03-13             2  25279966     4909590
..         ...    ...         ...           ...       ...         ...
0   2016-03-13     95  2016-03-13             2  21886644     4217237
0   2016-03-16     75  2016-03-16             5   1480518     3987926
0   2016-03-17     62  2016-03-17             6   1407005     1178106
0   2016-03-14     70  2016-03-14             3   1480518     3988018
1   2016-03-12     69  2016-03-12             1  32373289     6240901
0   2016-03-12    155  2016-03-12             1  31993940     6167184
2   2016-03-15    100  2016-03-15             4   9653086     4364989
1   2016-03-17     60  2016-03-17             6   9663343     1850260
0   2016-03-16    169  2016-03-16             5  12243051     7920541
1   2016-03-17    250  2016-03-17             6  10393465     2022303
0   2016-03-12    212  2016-03-12             1   1444340     1175376
1   2016-03-15    125  2016-03-15             4  20582119     6552654
2   2016-03-17    205  2016-03-17             6  20582119     6134867
0   2016-03-17     54  2016-03-17             6  19246369     3759239
2   2016-03-13     50  2016-03-13             2    204485     7634067
1   2016-03-13     90  2016-03-13             2  10850877     4553903
0   2016-03-18    175  2016-03-18             7  19357187     3890373
2   2016-03-16     89  2016-03-16             5  25742899     7281884
1   2016-03-18    129  2016-03-18             7  25499738     4996375
0   2016-03-16    110  2016-03-16             5    333210     4283698
2   2016-03-18     59  2016-03-18             7  15154687     5446995
1   2016-03-13    189  2016-03-13             2   1461240     1088876
0   2016-03-15    130  2016-03-15             4  24584716     6602217
1   2016-03-18    129  2016-03-18             7  25499738     4947526
1   2016-03-12     55  2016-03-12             1   5009446     7986820
3   2016-03-14     70  2016-03-14             3  42431392     8036024
0   2016-03-15    140  2016-03-15             4   4195134     6823628
0   2016-03-12    125  2016-03-12             1  27849429     8445701
2   2016-03-15    165  2016-03-15             4    319393       65329
0   2016-03-15     98  2016-03-15             4   8993560     4997112

[124 rows x 6 columns]

In [555]:
sorted_repo = sorted(mailing_repo.values(), key = lambda x: len(x))

In [556]:
mailing_list = []
for key, value in mailing_repo.iteritems():
        print key
        #print value
        print len(value.drop_duplicates() )
        mailing_list.append([[key],[len(value.drop_duplicates() )]])

mailing_list.sort(key=lambda x: x[1])        
tuple(mailing_list[0][0])[0]
mailing_repo ['orphan_more_advance_2w']

orphan_more_advance_more
305
orphan_1d_advance_more
421
orphan_1d_advance_1w
124
orphan_more_advance_1w
20
orphan_1d_advance_2w
94
orphan_more_advance_2w
44
orphan_2d_advance_more
615
orphan_3d_advance_more
421
orphan_3d_advance_2w
59
orphan_2d_advance_1w
131
orphan_3d_advance_1w
99
orphan_2d_advance_2w
100

          End  Price       Start  days_advance   host_id  listing_id
1  2016-03-28  112.0  2016-03-23            12  19036819     3727560
0  2016-03-24  280.0  2016-03-19             8  13822322     2769450
1  2016-03-24   80.0  2016-03-19             8   9898255     3294152
2  2016-03-26  225.0  2016-03-21            10      4804        9273
1  2016-03-26   65.0  2016-03-21            10  15561828     3057116
1  2016-03-29   98.0  2016-03-24            13  15501263     7480676
0  2016-03-27  200.0  2016-03-22            11   3011415     2848330
1  2016-03-24  209.0  2016-03-19             8     25188        9824
0  2016-03-27  200.0  2016-03-22            11   3011415     2848362
0  2016-03-24   99.0  2016-03-19             8  30841304     5940928
0  2016-03-28  400.0  2016-03-23            12   9410008     6629066
0  2016-03-25  325.0  2016-03-20             9  10477638     3721095
0  2016-03-28  200.0  2016-03-23            12   8114037     8390558
0  2016-03-28  395.0  2016-03-23            12   9039262     8194001
0  2016-03-24  154.2  2016-03-19             8   1444340      658029
0  2016-03-27  327.0  2016-03-22            11  12243051     7966114
0  2016-03-25  175.0  2016-03-20             9  25932315     5025015
0  2016-03-28  617.0  2016-03-23            12   9419684     6598203
0  2016-03-27   69.0  2016-03-22            11    847253      200265
0  2016-03-25  305.0  2016-03-20             9  23901135     4632511
0  2016-03-27  238.4  2016-03-22            11   9410008     8458210
0  2016-03-25   65.0  2016-03-20             9   4695018     5951665
0  2016-03-24  150.0  2016-03-19             8   3648427      708802
0  2016-03-25   80.0  2016-03-20             9   1416883     6410674
0  2016-03-28  300.0  2016-03-23            12  31235595     6017574
0  2016-03-24   50.0  2016-03-19             8   1730791      504515
0  2016-03-24   53.8  2016-03-19             8   6097281     1110769
0  2016-03-29  169.0  2016-03-24            13  20857768     4510513
0  2016-03-29  180.0  2016-03-24            13   2042090     6845352
0  2016-03-25  120.0  2016-03-20             9  17844905     7287822
0  2016-03-28  100.0  2016-03-23            12   1374514     3036349
0  2016-03-29  152.0  2016-03-24            13  15098486     6215248
0  2016-03-25   85.0  2016-03-20             9  22776068     8320775
0  2016-03-26  160.0  2016-03-21            10   5430185      989163
0  2016-03-26  390.0  2016-03-21            10  19742431     5666988
0  2016-03-26  295.0  2016-03-21            10    128280       29765
0  2016-03-26  195.0  2016-03-21            10      8229        6695
0  2016-03-28  199.0  2016-03-23            12  32278468     8428314
0  2016-03-29   60.0  2016-03-24            13   9663343     1850260
0  2016-03-27  273.0  2016-03-22            11  12243051     7634365
0  2016-03-29  185.0  2016-03-24            13  15760345     3276286
0  2016-03-25   55.0  2016-03-20             9   5009446     7986820
0  2016-03-25   80.0  2016-03-20             9    174986       40601
0  2016-03-26  165.0  2016-03-21            10    319393       65329

In [557]:
#size of the sample
sample_size = 20

#number of elements in the final dictionary
size= len(mailing_repo)


#this cycle uses an auxiliary dictionary, to analyze each remaining element per time and then put it on the final dictionary 
#and delete it from the auxiliary one

for i in range(size):
        print "elaborating element: " + str(i)
        
        mailing_list = []
        #auxiliary list for sorting by the one with less elements
        for key, value in mailing_repo.iteritems():
                #print key
                #print len(value.drop_duplicates() )
                mailing_list.append([[key],[len(value.drop_duplicates() )]])

        mailing_list.sort(key=lambda x: x[1])
        
        #the element currently analyzed is the first of the ordered list
        index = tuple(mailing_list[0][0])[0]
        
        #pick sample_size elments. They are picked from above, which is similar that taking them randomly
        mailing_repo[index]=mailing_repo[index].head(n=sample_size) 
        
        #print index
        #print len(mailing_repo[index]) 
        
        #insert in the result dictionary the current element 
        mailing_repo_def [index] = mailing_repo [index]
        
        #count = 1
        for key, value in mailing_repo.iteritems():
                #print key
                #print value.listing_id
                for id_el in value.listing_id:

                    #print "mailing list"
                    #print mailing_repo[mailing_list[0][0]]
                    for id_drop in mailing_repo[index].listing_id:
                        if id_el == id_drop and key!=index:
                            #df = df[df.line_race != 0] con df = mailing_repo [key]
                            #print key
                            #print index
                            #print "before " + str(mailing_repo [key].size )
                            mailing_repo[key] = mailing_repo[key][mailing_repo [key].listing_id!=id_el]
                            #print "after " + str(mailing_repo [key].size )
                            
                            #print "duplicate found at iteration " + str(i)
                            #count = count +1
        #delete the analyzed element from the auxiliary dictionary
        del mailing_repo [index]

print "\n"
print "**********OUTPUT************"  
print "\n"
for key, value in mailing_repo_def.iteritems():
        try:
            print "\n"
            print "ELEMENT: " + str(key)
            print "LENGTH: "+ str(len(value ))
            print "CONTENTS:"
            for id_el in value.listing_id:
                print id_el
        #print value
            
        except TypeError:
            print "empty element"
            pass

elaborating element: 0
elaborating element: 1
elaborating element: 2
elaborating element: 3
elaborating element: 4
elaborating element: 5
elaborating element: 6
elaborating element: 7
elaborating element: 8
elaborating element: 9
elaborating element: 10
elaborating element: 11


**********OUTPUT************




ELEMENT: orphan_more_advance_more
LENGTH: 20
CONTENTS:
7446573.0
7856323.0
5791960.0
663770.0
8634599.0
6881541.0
6725993.0
6709682.0
6939126.0
8274008.0
1425973.0
7242319.0
4948724.0
7775074.0
5940069.0
2943804.0
6390634.0
1090413.0
7611271.0
2933661.0


ELEMENT: orphan_1d_advance_more
LENGTH: 20
CONTENTS:
8339473.0
6627469.0
1704223.0
4080000.0
6160803.0
3285585.0
7578399.0
6742905.0
1147871.0
4359160.0
7840797.0
8271384.0
6554785.0
3917027.0
7939312.0
1428355.0
7292184.0
2278704.0
591248.0
6194602.0


ELEMENT: orphan_1d_advance_1w
LENGTH: 20
CONTENTS:
7708787.0
6643926.0
2998554.0
7528746.0
1220971.0
1178162.0
57800.0
6609546.0
3302294.0
3089505.0
1615033.0
6645010.0
6432655.0
5163162.0
8210702.0
4065578.0
1321422.0
4909590.0
8153848.0
1141522.0


ELEMENT: orphan_more_advance_1w
LENGTH: 20
CONTENTS:
8536127.0
5054601.0
3727560.0
2392462.0
9273.0
451872.0
6121709.0
2722165.0
5040534.0
6629929.0
7966317.0
5927267.0
7853079.0
3945704.0
3585343.0
22354.0
7633883.0
990668.0
6356533.0
540470.0


ELEMENT: orphan_1d_advance_2w
LENGTH: 20
CONTENTS:
4964365.0
7880828.0
2564544.0
6062890.0
7881551.0
5020055.0
6923446.0
4924910.0
6596242.0
6744206.0
4573388.0
4090224.0
5892953.0
6343532.0
568234.0
4820071.0
8670336.0
8096900.0
2395326.0
3591359.0


ELEMENT: orphan_more_advance_2w
LENGTH: 20
CONTENTS:
2769450.0
3294152.0
3057116.0
7480676.0
2848330.0
9824.0
2848362.0
5940928.0
6629066.0
3721095.0
8390558.0
8194001.0
658029.0
7966114.0
5025015.0
6598203.0
200265.0
4632511.0
8458210.0
5951665.0


ELEMENT: orphan_2d_advance_more
LENGTH: 20
CONTENTS:
7929879.0
5726250.0
6725762.0
4432035.0
7454966.0
5992501.0
8340072.0
4645486.0
4334206.0
377474.0
8200839.0
6316145.0
1934073.0
4457943.0
5481243.0
2360109.0
2843445.0
8454985.0
2843596.0
6972426.0


ELEMENT: orphan_3d_advance_more
LENGTH: 20
CONTENTS:
5729845.0
4793787.0
4695542.0
8371115.0
3802653.0
4687499.0
4638356.0
8537786.0
4892490.0
2795342.0
5146447.0
5146451.0
4015972.0
4261781.0
7825327.0
5146580.0
5957631.0
7743569.0
8366402.0
4098410.0


ELEMENT: orphan_3d_advance_2w
LENGTH: 20
CONTENTS:
3858697.0
7954808.0
2277821.0
4530670.0
5874408.0
754845.0
7931331.0
4105704.0
5269216.0
3442711.0
2549840.0
682093.0
3410087.0
4294835.0
6990023.0
830153.0
4549374.0
4025194.0
3615760.0
1887581.0


ELEMENT: orphan_2d_advance_1w
LENGTH: 20
CONTENTS:
7725279.0
5734770.0
4514653.0
6677469.0
6317304.0
1476154.0
9860.0
1107634.0
4759864.0
6801288.0
6465602.0
1067184.0
4532489.0
5933544.0
8112652.0
1525494.0
6171496.0
4287348.0
4860853.0
3730447.0


ELEMENT: orphan_3d_advance_1w
LENGTH: 20
CONTENTS:
163941.0
7741566.0
7495866.0
3309941.0
7332266.0
4303606.0
7692933.0
4178790.0
8627123.0
7472068.0
4662379.0
6006121.0
705900.0
6276572.0
6317722.0
5801643.0
1550047.0
1885825.0
7358714.0
2943299.0


ELEMENT: orphan_2d_advance_2w
LENGTH: 20
CONTENTS:
5153080.0
442735.0
5882411.0
8626752.0
66288.0
4997889.0
6292261.0
8422876.0
3392423.0
7693354.0
1115394.0
4580825.0
6661860.0
2295530.0
2000797.0
4573238.0
76073.0
1648950.0
6924700.0
5761461.0

In [558]:
mailing_repo_def

{'orphan_1d_advance_1w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-15    175  2016-03-15             4  16671525     7708787
 0  2016-03-16    135  2016-03-16             5   4298040     6643926
 0  2016-03-12    195  2016-03-12             1   3462813     2998554
 1  2016-03-13     60  2016-03-13             2   8892809     7528746
 0  2016-03-13    159  2016-03-13             2   5578043     1220971
 0  2016-03-13     41  2016-03-13             2   1407005     1178162
 0  2016-03-17     65  2016-03-17             6     68870       57800
 0  2016-03-17    150  2016-03-17             6  34584706     6609546
 0  2016-03-15    151  2016-03-15             4   1369968     3302294
 1  2016-03-13     75  2016-03-13             2   4104737     3089505
 0  2016-03-18     90  2016-03-18             7   3637081     1615033
 0  2016-03-16     55  2016-03-16             5  19782214     6645010
 0  2016-03-15    150  2016-03-15             4  28525504     6432655
 1  2016-03-17    271  2016-03-17             6  26704689     5163162
 2  2016-03-17    197  2016-03-17             6  28583327     8210702
 1  2016-03-14    179  2016-03-14             3  16779145     4065578
 0  2016-03-13     33  2016-03-13             2   6608084     1321422
 0  2016-03-13     90  2016-03-13             2  25279966     4909590
 0  2016-03-16    105  2016-03-16             5  28820575     8153848
 1  2016-03-13     45  2016-03-13             2   1407005     1141522,
 'orphan_1d_advance_2w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-19    180  2016-03-19             8   6104365     4964365
 0  2016-03-20     57  2016-03-20             9  41542719     7880828
 1  2016-03-20    179  2016-03-20             9    261895     2564544
 0  2016-03-20    199  2016-03-20             9  28272775     6062890
 1  2016-03-20    209  2016-03-20             9   1639654     7881551
 1  2016-03-24     65  2016-03-24            13  14095697     5020055
 0  2016-03-19    200  2016-03-19             8  36287718     6923446
 1  2016-03-24    150  2016-03-24            13  24997738     4924910
 3  2016-03-20    175  2016-03-20             9  11792930     6596242
 2  2016-03-24     60  2016-03-24            13   4192732     6744206
 2  2016-03-21    189  2016-03-21            10   5578043     4573388
 1  2016-03-21    225  2016-03-21            10  17783651     4090224
 2  2016-03-22     72  2016-03-22            11  17744599     5892953
 0  2016-03-20    255  2016-03-20             9  33037385     6343532
 2  2016-03-23     95  2016-03-23            12   2796082      568234
 1  2016-03-21     85  2016-03-21            10     93916     4820071
 3  2016-03-23    199  2016-03-23            12  21184200     8670336
 1  2016-03-20    160  2016-03-20             9  39652496     8096900
 2  2016-03-19    120  2016-03-19             8  12230539     2395326
 2  2016-03-21    120  2016-03-21            10   9662986     3591359,
 'orphan_1d_advance_more':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-04-19    200  2016-04-19            39  15396970     8339473
 0  2016-04-20    200  2016-04-20            40   4718853     6627469
 0  2016-04-15    495  2016-04-15            35   7759171     1704223
 0  2016-03-30     42  2016-03-30            19   6331373     4080000
 1  2016-03-27    225  2016-03-27            16  13124709     6160803
 0  2016-06-02   1100  2016-06-02            83  16605319     3285585
 0  2016-04-03    200  2016-04-03            23  25491429     7578399
 0  2016-04-11    140  2016-04-11            31    324630     6742905
 2  2016-04-16    200  2016-04-16            36   1407005     1147871
 0  2016-04-10    140  2016-04-10            30    324630     4359160
 0  2016-04-25    461  2016-04-25            45   4962900     7840797
 1  2016-04-15    150  2016-04-15            35  43613912     8271384
 2  2016-04-13    155  2016-04-13            33  28123912     6554785
 0  2016-04-16     82  2016-04-16            36   6331373     3917027
 2  2016-06-02     95  2016-06-02            83    229882     7939312
 0  2016-03-31    140  2016-03-31            20   7422781     1428355
 0  2016-04-16     80  2016-04-16            36  11544688     7292184
 0  2016-04-15     69  2016-04-15            35  11631886     2278704
 0  2016-04-10     47  2016-04-10            30    814202      591248
 0  2016-03-31    175  2016-03-31            20   3103040     6194602,
 'orphan_2d_advance_1w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-16     30  2016-03-15             4  38701026     7725279
 0  2016-03-16    150  2016-03-15             4  27015747     5734770
 0  2016-03-15     54  2016-03-14             3  15154687     4514653
 2  2016-03-19    245  2016-03-18             7  34949685     6677469
 1  2016-03-13    166  2016-03-12             1   4170200     6317304
 1  2016-03-14    120  2016-03-13             2   7900241     1476154
 2  2016-03-16    263  2016-03-15             4     25188        9860
 2  2016-03-19    350  2016-03-18             7   6081409     1107634
 0  2016-03-19    180  2016-03-18             7  24560453     4759864
 0  2016-03-15     46  2016-03-14             3   1299837     6801288
 0  2016-03-15     43  2016-03-14             3    635157     6465602
 1  2016-03-19     55  2016-03-18             7    848706     1067184
 0  2016-03-15     54  2016-03-14             3  15154687     4532489
 2  2016-03-17    300  2016-03-16             5  30808826     5933544
 0  2016-03-16     55  2016-03-15             4  30489899     8112652
 0  2016-03-15     32  2016-03-14             3   8139434     1525494
 0  2016-03-15    125  2016-03-14             3   6213232     6171496
 1  2016-03-13     90  2016-03-12             1  22257404     4287348
 0  2016-03-15     98  2016-03-14             3    814298     4860853
 2  2016-03-19    140  2016-03-18             7   9329890     3730447,
 'orphan_2d_advance_2w':           End  Price       Start  days_advance   host_id  listing_id
 2  2016-03-22    100  2016-03-21            10   2594165     5153080
 1  2016-03-21    206  2016-03-20             9   1592221      442735
 0  2016-03-20     78  2016-03-19             8  18807469     5882411
 0  2016-03-22     65  2016-03-21            10   9492322     8626752
 0  2016-03-21     73  2016-03-20             9    324630       66288
 0  2016-03-25     90  2016-03-24            13  14080573     4997889
 0  2016-03-20     99  2016-03-19             8  21851356     6292261
 0  2016-03-22     99  2016-03-21            10  21851356     8422876
 0  2016-03-24    115  2016-03-23            12   3462813     3392423
 0  2016-03-23     65  2016-03-22            11  28184994     7693354
 2  2016-03-21     63  2016-03-20             9    884747     1115394
 0  2016-03-24    189  2016-03-23            12   5578043     4580825
 0  2016-03-21     65  2016-03-20             9  19008767     6661860
 0  2016-03-21     97  2016-03-20             9  11725202     2295530
 0  2016-03-22     43  2016-03-21            10   9898255     2000797
 0  2016-03-21    179  2016-03-20             9   5578043     4573238
 1  2016-03-24    400  2016-03-23            12    405376       76073
 0  2016-03-21    140  2016-03-20             9   1369968     1648950
 1  2016-03-25    215  2016-03-24            13  20582119     6924700
 2  2016-03-21    115  2016-03-20             9  29514895     5761461,
 'orphan_2d_advance_more':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-04-22    226  2016-04-21            41   1444340     7929879
 1  2016-03-31    375  2016-03-30            19  29688938     5726250
 0  2016-03-29     64  2016-03-28            17    635157     6725762
 0  2016-04-12    195  2016-04-11            31  22892596     4432035
 0  2016-04-04     65  2016-04-03            23  16442921     7454966
 0  2016-04-11    167  2016-04-10            30   1538079     5992501
 0  2016-04-13    225  2016-04-12            32  43959997     8340072
 0  2016-04-14    500  2016-04-13            33  24050914     4645486
 0  2016-04-15    200  2016-04-14            34  22503918     4334206
 0  2016-04-13    395  2016-04-12            32    119019      377474
 0  2016-05-10    125  2016-05-09            59  43217109     8200839
 0  2016-04-06    205  2016-04-05            25  32860113     6316145
 0  2016-04-13    225  2016-04-12            32    546854     1934073
 2  2016-04-20    130  2016-04-19            39  20912254     4457943
 0  2016-04-02    150  2016-04-01            21  28425476     5481243
 0  2016-04-10    175  2016-04-09            29   9967305     2360109
 0  2016-03-30     75  2016-03-29            18   3164508     2843445
 0  2016-04-23    250  2016-04-22            42  15151322     8454985
 0  2016-03-28    103  2016-03-27            16   3351569     2843596
 1  2016-05-03    575  2016-05-02            52  36559227     6972426,
 'orphan_3d_advance_1w':           End  Price       Start  days_advance   host_id  listing_id
 1  2016-03-15  125.0  2016-03-13             2      8229      163941
 0  2016-03-15   79.0  2016-03-13             2  26956083     7741566
 0  2016-03-14  129.0  2016-03-12             1  38015635     7495866
 0  2016-03-17  309.0  2016-03-15             4   9419684     3309941
 0  2016-03-15   85.0  2016-03-13             2  31340713     7332266
 0  2016-03-16  115.0  2016-03-14             3  21851356     4303606
 0  2016-03-16   59.0  2016-03-14             3   9508341     7692933
 0  2016-03-16  206.5  2016-03-14             3   1444340     4178790
 0  2016-03-18   69.0  2016-03-16             5  15723690     8627123
 0  2016-03-14  132.0  2016-03-12             1  38188681     7472068
 0  2016-03-17  350.0  2016-03-15             4  24124767     4662379
 0  2016-03-15   84.0  2016-03-13             2  23208278     6006121
 0  2016-03-15  119.0  2016-03-13             2    508268      705900
 2  2016-03-20  189.0  2016-03-18             7  11071285     6276572
 0  2016-03-16  101.0  2016-03-14             3   9410008     6317722
 0  2016-03-14   41.0  2016-03-12             1  30099169     5801643
 0  2016-03-16  230.0  2016-03-14             3   1444340     1550047
 0  2016-03-14   60.0  2016-03-12             1   6391436     1885825
 0  2016-03-18  137.0  2016-03-16             5  12243051     7358714
 1  2016-03-17   55.0  2016-03-15             4  15026714     2943299,
 'orphan_3d_advance_2w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-23  175.0  2016-03-21            10  19907707     3858697
 0  2016-03-22  229.0  2016-03-20             9  12243051     7954808
 1  2016-03-23  177.5  2016-03-21            10   9410008     2277821
 0  2016-03-23   75.0  2016-03-21            10  23490243     4530670
 2  2016-03-23   60.0  2016-03-21            10  24337472     5874408
 0  2016-03-24  209.0  2016-03-22            11     25188      754845
 0  2016-03-23  239.0  2016-03-21            10  12243051     7931331
 0  2016-03-24  120.0  2016-03-22            11  21299112     4105704
 0  2016-03-22  235.5  2016-03-20             9   1444340     5269216
 2  2016-03-22  126.0  2016-03-20             9  17351265     3442711
 2  2016-03-22  268.5  2016-03-20             9    814298     2549840
 0  2016-03-24   84.0  2016-03-22            11   3474193      682093
 0  2016-03-22  119.0  2016-03-20             9  17194624     3410087
 0  2016-03-24   35.0  2016-03-22            11   9189449     4294835
 0  2016-03-21   62.5  2016-03-19             8  22500410     6990023
 0  2016-03-24  112.0  2016-03-22            11    206353      830153
 0  2016-03-22  145.0  2016-03-20             9  18286028     4549374
 1  2016-03-23   70.0  2016-03-21            10   1480518     4025194
 0  2016-03-23   98.0  2016-03-21            10  17000652     3615760
 0  2016-03-22  300.0  2016-03-20             9    970787     1887581,
 'orphan_3d_advance_more':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-28     59  2016-03-28            17  29709417     5729845
 1  2016-04-21     69  2016-04-21            41  24658662     4793787
 1  2016-04-15     69  2016-04-15            35  23953876     4695542
 0  2016-03-27    180  2016-03-27            16   3179912     8371115
 0  2016-03-31     64  2016-03-31            20  19246369     3802653
 1  2016-03-29     68  2016-03-29            18   4540666     4687499
 0  2016-04-15    130  2016-04-15            35  24014785     4638356
 1  2016-03-29     80  2016-03-29            18  44948848     8537786
 0  2016-04-14     45  2016-04-14            34  25078045     4892490
 0  2016-03-28    109  2016-03-28            17  14299585     2795342
 0  2016-04-15     60  2016-04-15            35   9663343     5146447
 0  2016-04-15     60  2016-04-15            35   9663343     5146451
 1  2016-03-28     50  2016-03-28            17  14303759     4015972
 0  2016-03-29    200  2016-03-29            18  17814164     4261781
 0  2016-05-03    450  2016-05-03            53  14785487     7825327
 0  2016-04-15     60  2016-04-15            35   9663343     5146580
 0  2016-06-02    135  2016-06-02            83  15501263     5957631
 0  2016-04-02     87  2016-04-02            22   4595799     7743569
 0  2016-04-19    180  2016-04-19            39  44095138     8366402
 0  2016-05-13    105  2016-05-13            63  11487565     4098410,
 'orphan_more_advance_1w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-18  250.0  2016-03-13             2  39459066     8536127
 0  2016-03-18   63.8  2016-03-13             2  26098645     5054601
 0  2016-03-18  120.0  2016-03-13             2  19036819     3727560
 0  2016-03-18   55.0  2016-03-13             2  12221171     2392462
 1  2016-03-19  225.0  2016-03-14             3      4804        9273
 1  2016-03-18   99.0  2016-03-13             2   2244581      451872
 0  2016-03-23  200.0  2016-03-18             7  19044311     6121709
 0  2016-03-17  232.0  2016-03-12             1  13929879     2722165
 0  2016-03-17   45.0  2016-03-12             1  25078045     5040534
 0  2016-03-18   95.0  2016-03-13             2     63525     6629929
 0  2016-03-22   92.6  2016-03-17             6   3333785     7966317
 0  2016-03-17   65.2  2016-03-12             1  26098645     5927267
 0  2016-03-17  290.2  2016-03-12             1    814298     7853079
 0  2016-03-18   87.0  2016-03-13             2  20447366     3945704
 1  2016-03-18  110.0  2016-03-13             2  10332798     3585343
 0  2016-03-18  125.0  2016-03-13             2     85770       22354
 0  2016-03-18  514.4  2016-03-13             2    814298     7633883
 0  2016-03-17   90.4  2016-03-12             1   1651480      990668
 0  2016-03-18  317.0  2016-03-13             2   9419684     6356533
 0  2016-03-18   98.0  2016-03-13             2   2656376      540470,
 'orphan_more_advance_2w':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-03-24  280.0  2016-03-19             8  13822322     2769450
 1  2016-03-24   80.0  2016-03-19             8   9898255     3294152
 1  2016-03-26   65.0  2016-03-21            10  15561828     3057116
 1  2016-03-29   98.0  2016-03-24            13  15501263     7480676
 0  2016-03-27  200.0  2016-03-22            11   3011415     2848330
 1  2016-03-24  209.0  2016-03-19             8     25188        9824
 0  2016-03-27  200.0  2016-03-22            11   3011415     2848362
 0  2016-03-24   99.0  2016-03-19             8  30841304     5940928
 0  2016-03-28  400.0  2016-03-23            12   9410008     6629066
 0  2016-03-25  325.0  2016-03-20             9  10477638     3721095
 0  2016-03-28  200.0  2016-03-23            12   8114037     8390558
 0  2016-03-28  395.0  2016-03-23            12   9039262     8194001
 0  2016-03-24  154.2  2016-03-19             8   1444340      658029
 0  2016-03-27  327.0  2016-03-22            11  12243051     7966114
 0  2016-03-25  175.0  2016-03-20             9  25932315     5025015
 0  2016-03-28  617.0  2016-03-23            12   9419684     6598203
 0  2016-03-27   69.0  2016-03-22            11    847253      200265
 0  2016-03-25  305.0  2016-03-20             9  23901135     4632511
 0  2016-03-27  238.4  2016-03-22            11   9410008     8458210
 0  2016-03-25   65.0  2016-03-20             9   4695018     5951665,
 'orphan_more_advance_more':           End  Price       Start  days_advance   host_id  listing_id
 0  2016-04-29  199.0  2016-04-24            44  11541727     7446573
 0  2016-06-02  184.4  2016-05-28            78  12243051     7856323
 0  2016-04-15  222.2  2016-04-10            30    814298     5791960
 0  2016-04-01  125.0  2016-03-27            16   3274255      663770
 0  2016-04-15  169.0  2016-04-10            30  45402419     8634599
 0  2016-04-15  199.0  2016-04-10            30  13124709     6881541
 0  2016-04-10   59.4  2016-04-05            25    635157     6725993
 0  2016-04-14   65.0  2016-04-09            29    212445     6709682
 0  2016-04-15  150.0  2016-04-10            30  36379082     6939126
 0  2016-04-13  135.0  2016-04-08            28  38403389     8274008
 0  2016-04-15  350.0  2016-04-10            30   1015632     1425973
 0  2016-03-31  250.0  2016-03-26            15  37919897     7242319
 0  2016-04-15  249.0  2016-04-10            30    508268     4948724
 0  2016-06-03  550.0  2016-05-29            79  39536288     7775074
 1  2016-04-15  384.0  2016-04-10            30   8479265     5940069
 0  2016-04-15  190.0  2016-04-10            30     50866     2943804
 0  2016-04-14   75.0  2016-04-09            29   2810446     6390634
 1  2016-04-13  118.0  2016-04-08            28   1984434     1090413
 0  2016-05-20  591.0  2016-05-15            65    953185     7611271
 0  2016-05-13   50.0  2016-05-08            58  11487565     2933661}

In [559]:
mailing_final = {}
for k, v in mailing_repo_def.iteritems():
    mailing_final[k] = pd.merge(v, listings_original, left_on='listing_id', right_on = 'id', how='inner')

In [560]:
mailing_final.values()[0].columns

Index([u'End', u'Price', u'Start', u'days_advance', u'host_id_x',
       u'listing_id', u'id', u'listing_url', u'name', u'host_id_y',
       u'host_url', u'host_name', u'host_response_time', u'host_response_rate',
       u'host_acceptance_rate', u'host_is_superhost',
       u'host_total_listings_count', u'monthly_price', u'minimum_nights',
       u'number_of_reviews', u'instant_bookable', u'room_type', u'bedrooms'],
      dtype='object')

# Generating Messages

In [651]:
'''
Hi, my name is Michele  and I am interested in staying at your place for 1 day from 3/20/16 to 3/21/16. 
The calendar is open on these days and I am wondering if it is still available? 

A little bit more about myself: I am a graduate student from Milan, Italy and study Communication Design.
I will visit Boston a few times this year to work on a project with a local school. 
I am fond of exploring cultures and visual arts around the world.

I am wondering if you would be willing to lower the rate to $85/night? The trip is really soon and my schedule matches perfectly with the opening in your calendar. So I would be willing to make the booking immediately if the price is ok with you.

'''

import datetime
def calculate_duration(start, end):
    start = datetime.datetime.strptime(start, '%Y-%m-%d')
    end = datetime.datetime.strptime(end, '%Y-%m-%d')

    days_in_advance = (end - start).days
    return days_in_advance

def generateMessage(host_name, start, end, price, num_guests):
    #this is a list storing all reasons for each 
    days_advance = (datetime.datetime.strptime(start, '%Y-%m-%d') - datetime.datetime.today()).days
    if days_advance < 7:
        reason = " Since the trip is coming up very soon, and I found my schedule matches perfectly with the opening in your calendar,"
    else: 
        reason = " Because my schedule match perfectly with the opening in your calendar,"

    duration = calculate_duration(start, end)
    if duration == 1:
        duration = str(duration) + ' day'
    else:
        duration = str(duration) + ' days'
        
    message_1 = 'Hi {}, my name is Michele and I am interested in staying at your place for {}, from {} to {}. The calendar is open on these days and I am wondering if it is still available? '.format(host_name ,duration, start , end)
    
    message_2 = 'A little bit more about myself: I am a graduate student from Milan, Italy and study Communication Design. I am fond of exploring cultures and visual arts around the world.'
    
    message_3 = '{} I am wondering if you would be willing to lower the rate to ${}/night? I would be willing to make the booking immediately if the price is ok with you.'.format(reason,price)
        
    if(num_guests==1 or num_guests==0 or np.isnan(num_guests)):
        return message_1 + message_2 + message_3
    elif (num_guests ==2 ):
        addition_two_persons = 'I will visit Boston a few times this year to work on a project with a local school. I will be there with a collegue of mine. '
        return message_1 + message_2 + addition_two_persons + message_3
    else: 
        addition_n_persons = 'I will visit Boston a few times this year to work on a project with a local school. I will be there with {} collegues of mine. '.format(int(num_guests - 1))
        return message_1 + message_2 + addition_n_persons + message_3

In [652]:
np.isnan(NaN)

NameError: name 'NaN' is not defined

# Generate all messages

In [653]:
messages = {}
discount = [0.6, 0.7, 0.8]

def getDiscountPrice(price, discount):
    return 5 * (int(price * discount) / 5)

for k, v in mailing_final.iteritems():
    msg_list = [] 
    discount_list = []
    for index, row in v.iterrows():
        msg = generateMessage(row['host_name'], row['Start'], row['End'], getDiscountPrice(row['Price'], discount[index % 3]), row['bedrooms'])
        msg_list.append(msg)
        discount_list.append(discount[index % 3])
    mailing_final[k]['messages'] = msg_list
    mailing_final[k]['discount_asked'] = discount_list

In [658]:
for k, v in mailing_final.iteritems():
    v.to_json('final_messages/{}.json'.format(k))

In [659]:
pd.read_json('final_messages/orphan_more_advance_more.json')

,End,Price,Start,bedrooms,days_advance,discount_asked,host_acceptance_rate,host_id_x,host_id_y,host_is_superhost,...,id,instant_bookable,listing_id,listing_url,messages,minimum_nights,monthly_price,name,number_of_reviews,room_type
0,2016-04-29,199.0,2016-04-24,1,44,0.6,100%,11541727,11541727,f,...,7446573,f,7446573,https://www.airbnb.com/rooms/7446573,"Hi Ainsley, my name is Michele and I am intere...",2,None,"North End GEM! 1Bed, 1Bath with AC!",2,Entire home/apt
1,2016-06-02,184.4,2016-05-28,0,78,0.7,98%,12243051,12243051,f,...,7856323,t,7856323,https://www.airbnb.com/rooms/7856323,"Hi Flatbook, my name is Michele and I am inter...",3,None,Fabulously Central Apt by Flatbook,0,Entire home/apt
10,2016-04-15,350.0,2016-04-10,1,30,0.7,100%,1015632,1015632,f,...,1425973,f,1425973,https://www.airbnb.com/rooms/1425973,"Hi Kevin, my name is Michele and I am interest...",2,None,Historic brick Victorian row house,11,Private room
11,2016-03-31,250.0,2016-03-26,1,15,0.8,68%,37919897,37919897,f,...,7242319,f,7242319,https://www.airbnb.com/rooms/7242319,"Hi Katie, my name is Michele and I am interest...",1,None,Luxury apartment near North Station,8,Entire home/apt
12,2016-04-15,249.0,2016-04-10,1,30,0.6,93%,508268,508268,f,...,4948724,f,4948724,https://www.airbnb.com/rooms/4948724,"Hi Richard, my name is Michele and I am intere...",3,None,Carlyle 5th Floor: by Spare Suite,4,Entire home/apt
13,2016-06-03,550.0,2016-05-29,2,79,0.7,100%,39536288,39536288,f,...,7775074,f,7775074,https://www.airbnb.com/rooms/7775074,"Hi Alex, my name is Michele and I am intereste...",1,None,"Luxurious, spacey apt. in Cambridge",2,Entire home/apt
14,2016-04-15,384.0,2016-04-10,2,30,0.8,78%,8479265,8479265,f,...,5940069,f,5940069,https://www.airbnb.com/rooms/5940069,"Hi Alejandro, my name is Michele and I am inte...",1,None,❤️of Boston.2br Perf. For marathon,11,Entire home/apt
15,2016-04-15,190.0,2016-04-10,2,30,0.6,53%,50866,50866,f,...,2943804,f,2943804,https://www.airbnb.com/rooms/2943804,"Hi SleepAfloat, my name is Michele and I am in...",2,None,Yacht Rental Lola Downtown Boston!,5,Entire home/apt
16,2016-04-14,75.0,2016-04-09,1,29,0.7,100%,2810446,2810446,t,...,6390634,f,6390634,https://www.airbnb.com/rooms/6390634,"Hi Danielle, my name is Michele and I am inter...",2,None,"Location, Charm, and Style!",16,Private room
17,2016-04-13,118.0,2016-04-08,1,28,0.8,100%,1984434,1984434,f,...,1090413,t,1090413,https://www.airbnb.com/rooms/1090413,"Hi Irene, my name is Michele and I am interest...",1,"$4,000.00","Prudential Ctr. Lge Room, Pvt. Bath",29,Private room
18,2016-05-20,591.0,2016-05-15,3,65,0.6,67%,953185,953185,f,...,7611271,f,7611271,https://www.airbnb.com/rooms/7611271,"Hi Katie, my name is Michele and I am interest...",2,None,"Elegant 3BD|2.5BA Near Ocean, BCEC",4,Entire home/apt
19,2016-05-13,50.0,2016-05-08,1,58,0.7,81%,11487565,11487565,f,...,2933661,f,2933661,https://www.airbnb.com/rooms/2933661,"Hi Josefa, my name is Michele and I am interes...",1,None,Private Room w/Porch. A JP experien,12,Private room
2,2016-04-15,222.2,2016-04-10,1,30,0.8,62%,814298,814298,f,...,5791960,f,5791960,https://www.airbnb.com/rooms/5791960,"Hi Brent, my name is Michele and I am interest...",3,None,"1 Bedroom apt. on Newbury, Back Bay",5,Entire home/apt
3,2016-04-01,125.0,2016-03-27,1,16,0.6,64%,3274255,3274255,f,...,663770,f,663770,https://www.airbnb.com/rooms/663770,"Hi Bella, my name is Michele and I am interest...",3,"$1,800.00","Queen-MGH, Beacon Hill, West End",14,Private room
4,2016-04-15,169.0,2016-04-10,1,30,0.7,None,45402419,45402419,f,...,8634599,f,8634599,https://www.airbnb.com/rooms/8634599,"Hi Jil, my name is Michele and I am interested...",1,"$2,399.00",Elegant suite in historic victorian,0,Entire home/apt
5,2016-04-15,199.0,2016-04-10,3,30,0.8,99%,13124709,13124709,t,...,6881541,f,6881541,https://www.airbnb.com/rooms/6881541,"Hi Thomas & Jenny, my name is Michele and I am...",1,None,"Charming 3BR, 1BA- 5 min to Boston",4,Entire home/apt
6,2016-04-10,59.4,2016-04-05,1,25,0.6,80%,635157,635157,f,...,6725993,f,6725993,https://www.airbnb.com/rooms/6725993,"Hi Catlin, my name is Michele and I am interes...",2,"$1,200.00",Sand room - Near colleges & parks,4,Private room
7,2016-04-14,65.0,2016-04-09,1,29,0.7,86%,212445,212445,f,...,6709682,f,6709682,https://www.airbnb.com/rooms/6709682,"Hi Emma, my name is Michele and I am intereste...",3,"$1,450.00",Private room in Boston,9,Private room
8,2016-04-15,150.0,2016-04-10,1,30,0.8,100%,36379082,36379082,f,...,6939126,f,6939126,https://www.airbnb.com/rooms/6939126,"Hi Tara, my name is Michele and I am intereste...",1,None,Cozy Studio ;-) in SOUTH END Boston,12,Entire home/apt
9,2016-04-13,135.0,2016-04-08,1,28,0.6,96%,38403389,38403389,f,...,8274008,f,8274008,https://www.airbnb.com/rooms/8274008,"Hi Katarzyna, my name is Michele and I am inte...",2,None,Private Bedroom S.Boston near BCEC.,5,Private room

In [634]:
pd.read_json('final_messages/orphan_more_advance_more.json')[:4]['messages'][0]

u'Hi Ainsley, my name is Michele and I am interested in staying at your place for 5 days, from 2016-04-24 to 2016-04-29. The calendar is open on these days and I am wondering if it is still available? A little bit more about myself: I am a graduate student from Milan, Italy and study Communication Design. I am fond of exploring cultures and visual arts around the world. Because my schedule match perfectly with the opening in your calendar, I am wondering if you would be willing to lower the rate to $115/night? I would be willing to make the booking immediately if the price is ok with you.'

In [630]:
test = pd.read_json('final_messages/orphan_more_advance_more.json')
print test['Start'][0]
print test['End'][0]
print test['listing_url'][0]
print test['listing_id'][0]
print test['messages'][0],

2016-04-24
2016-04-29
https://www.airbnb.com/rooms/7446573
7446573
Hi Ainsley, my name is Michele and I am interested in staying at your place for 5 days, from 2016-04-24 to 2016-04-29. The calendar is open on these days and I am wondering if it is still available? A little bit more about myself: I am a graduate student from Milan, Italy and study Communication Design. I am fond of exploring cultures and visual arts around the world. Because my schedule match perfectly with the opening in your calendar, I am wondering if you would be willing to lower the rate to $115/night? I would be willing to make the booking immediately if the price is ok with you.

In [657]:
generateMessage('qing', '2016-04-24', '2016-04-29', 100, 0)

'Hi qing, my name is Michele and I am interested in staying at your place for 5 days, from 2016-04-24 to 2016-04-29. The calendar is open on these days and I am wondering if it is still available? A little bit more about myself: I am a graduate student from Milan, Italy and study Communication Design. I am fond of exploring cultures and visual arts around the world. Because my schedule match perfectly with the opening in your calendar, I am wondering if you would be willing to lower the rate to $100/night? I would be willing to make the booking immediately if the price is ok with you.'